switch (TheSelection) do {
	case 2: { ["ACE_fieldDressing", "Gauze Bandage", "deliveries"] call A3M_fnc_buyItem; };
	case 3: { ["ACE_packingBandage", "Packing Bandage", "deliveries"] call A3M_fnc_buyItem; };
	case 4: { ["ACE_elasticBandage", "Elastic Bandage", "deliveries"] call A3M_fnc_buyItem; };
	case 5: { ["ACE_tourniquet", "Tourniquet", "deliveries"] call A3M_fnc_buyItem; };
	case 6: { ["ACE_morphine", "Morphine Autoinjector", "deliveries"] call A3M_fnc_buyItem; };
	case 7: { ["ACE_atropine", "Atropin Autoinjector", "deliveries"] call A3M_fnc_buyItem; };
	case 8: { ["ACE_epinephrine", "Epinephrine", "deliveries"] call A3M_fnc_buyItem; };
	case 9: { ["ACE_plasmaIV", "Plasma IV (1000ml)", "deliveries"] call A3M_fnc_buyItem; };
	case 10: { ["ACE_plasmaIV_500", "Plasma IV (500ml)", "deliveries"] call A3M_fnc_buyItem; };
	case 11: { ["ACE_plasmaIV_250", "Plasma IV (250 ml)", "deliveries"] call A3M_fnc_buyItem; };
	case 12: { ["ACE_bloodIV", "Blood IV (1000 ml)", "deliveries"] call A3M_fnc_buyItem; };
	case 13: { ["ACE_bloodIV_500", "Blood IV (500 ml)", "deliveries"] call A3M_fnc_buyItem; };
	case 14: { ["ACE_bloodIV_250", "Blood IV (250 ml)", "deliveries"] call A3M_fnc_buyItem; };
	case 15: { ["ACE_salineIV", "Saline IV (1000 ml)", "deliveries"] call A3M_fnc_buyItem; };
	case 16: { ["ACE_salineIV_500", "Saline IV (500 ml)", "deliveries"] call A3M_fnc_buyItem; };
	case 17: { ["ACE_salineIV_250", "Saline IV (250 ml)", "deliveries"] call A3M_fnc_buyItem; };
	case 18: { ["ACE_quikclot", "QuikClot Field Dressing", "deliveries"] call A3M_fnc_buyItem; };
	case 19: { ["ACE_personalAidKit", "Personal Aid Kit", "deliveries"] call A3M_fnc_buyItem; };
	case 20: { ["ACE_surgicalKit", "Surgical Kit", "deliveries"] call A3M_fnc_buyItem; };
	case 21: { ["ACE_bodyBag", "Body Bag", "deliveries"] call A3M_fnc_buyItem; };
};
