switch (TheSelection) do {
    case 0 : {["B_AssaultPack_blk", "Assault Pack (Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 1 : {["B_AssaultPack_cbr", "Assault Pack (Coyote)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 2 : {["B_AssaultPack_dgtl", "Assault Pack (Digital)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 3 : {["B_AssaultPack_rgr", "Assault Pack (Green)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 4 : {["B_AssaultPack_ocamo", "Assault Pack (Hex)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 5 : {["B_AssaultPack_khk", "Assault Pack (Khaki)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 6 : {["B_AssaultPack_mcamo", "Assault Pack (MTP)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 7 : {["B_AssaultPack_eaf_F", "Assault Pack (Geometric)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 8 : {["B_AssaultPack_wdl_F", "Assault Pack (Woodland)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 9 : {["B_Bergen_dgtl_F", "Bergen Backpack (Digital)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 10 : {["B_Bergen_hex_F", "Bergen Backpack (Hex)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 11 : {["B_Bergen_mcamo_F", "Bergen Backpack (MTP)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 12 : {["B_Bergen_tna_F", "Bergen Backpack (Tropic)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 13 : {["B_Bergen_ghex_F", "Bergen Backpack (Green Hex)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 14 : {["B_Carryall_blk", "Carryall Backpack (Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 15 : {["B_Carryall_cbr", "Carryall Backpack (Coyote)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 16 : {["B_Carryall_ocamo", "Carryall Backpack (Hex)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 17 : {["B_Carryall_khk", "Carryall Backpack (Khaki)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 18 : {["B_Carryall_mcamo", "Carryall Backpack (MTP)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 19 : {["B_Carryall_oli", "Carryall Backpack (Olive)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 20 : {["B_Carryall_oucamo", "Carryall Backpack (Urban)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 21 : {["B_Carryall_eaf_F", "Carryall Backpack (Geometric)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 22 : {["B_Carryall_green_F", "Carryall Backpack (Green)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 23 : {["B_Carryall_taiga_F", "Carryall Backpack (Taiga)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 24 : {["B_Carryall_wdl_F", "Carryall Backpack (Woodland)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 25 : {["B_FieldPack_blk", "Field Pack (Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 26 : {["B_FieldPack_cbr", "Field Pack (Coyote)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 27 : {["B_FieldPack_ocamo", "Field Pack (Hex)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 28 : {["B_FieldPack_khk", "Field Pack (Khaki)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 29 : {["B_FieldPack_oli", "Field Pack (Olive)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 30 : {["B_FieldPack_oucamo", "Field Pack (Urban)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 31 : {["B_FieldPack_ghex_F", "Field Pack (Green Hex)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 32 : {["B_FieldPack_green_F", "Field Pack (Green)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 33 : {["B_FieldPack_taiga_F", "Field Pack (Taiga)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 34 : {["B_Kitbag_cbr", "Kitbag (Coyote)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 35 : {["B_Kitbag_rgr", "Kitbag (Green)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 36 : {["B_Kitbag_mcamo", "Kitbag (MTP)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 37 : {["B_Kitbag_sgg", "Kitbag (Sage)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 38 : {["B_Kitbag_tan", "Kitbag (Tan)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 39 : {["B_TacticalPack_blk", "Tactical Backpack (Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 40 : {["B_TacticalPack_rgr", "Tactical Backpack (Green)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 41 : {["B_TacticalPack_ocamo", "Tactical Backpack (Hex)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 42 : {["B_TacticalPack_mcamo", "Tactical Backpack (MTP)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 43 : {["B_TacticalPack_oli", "Tactical Backpack (Olive)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 44 : {["B_ViperHarness_blk_F", "Viper Harness (Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 45 : {["B_ViperHarness_ghex_F", "Viper Harness (Green Hex)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 46 : {["B_ViperHarness_hex_F", "Viper Harness (Hex)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 47 : {["B_ViperHarness_khk_F", "Viper Harness (Khaki)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 48 : {["B_ViperHarness_oli_F", "Viper Harness (Olive)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 49 : {["B_ViperLightHarness_blk_F", "Viper Light Harness (Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 50 : {["B_ViperLightHarness_ghex_F", "Viper Light Harness (Green Hex)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 51 : {["B_ViperLightHarness_hex_F", "Viper Light Harness (Hex)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 52 : {["B_ViperLightHarness_khk_F", "Viper Light Harness (Khaki)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 53 : {["B_ViperLightHarness_oli_F", "Viper Light Harness (Olive)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 54 : {["B_LegStrapBag_black_F", "Leg Strap Bag (Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 55 : {["B_LegStrapBag_coyote_F", "Leg Strap Bag (Coyote)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 56 : {["B_LegStrapBag_olive_F", "Leg Strap Bag (Olive)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 57 : {["B_Messenger_Black_F", "Messenger Bag (Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 58 : {["B_Messenger_Coyote_F", "Messenger Bag (Coyote)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 59 : {["B_Messenger_Gray_F", "Messenger Bag (Gray)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 60 : {["B_Messenger_Olive_F", "Messenger Bag (Olive)", "TypeOfItem"] call A3M_fnc_buyItem; };
};
