switch (TheSelection) do {
    case 0: { ["B_AssaultPack_blk", "Assault Pack (Black)", "backpack"] call A3M_fnc_buyItem; };
    case 1: { ["B_AssaultPack_blk_DiverTL", "Assault Pack (Black) - Diver Team Leader", "backpack"] call A3M_fnc_buyItem; };
    case 2: { ["B_AssaultPack_blk_DiverExp", "Assault Pack (Black) - Diver Explosives", "backpack"] call A3M_fnc_buyItem; };
    case 3: { ["B_AssaultPack_cbr", "Assault Pack (Coyote)", "backpack"] call A3M_fnc_buyItem; };
    case 4: { ["B_AssaultPack_dgtl", "Assault Pack (Digi)", "backpack"] call A3M_fnc_buyItem; };
    case 5: { ["B_AssaultPack_rgr", "Assault Pack (Green)", "backpack"] call A3M_fnc_buyItem; };
    case 6: { ["B_AssaultPack_rgr_Repair", "Assault Pack (Green) - Engineer", "backpack"] call A3M_fnc_buyItem; };
    case 7: { ["B_AssaultPack_rgr_Medic", "Assault Pack (Green) - Medic", "backpack"] call A3M_fnc_buyItem; };
    case 8: { ["B_AssaultPack_ocamo", "Assault Pack (Hex)", "backpack"] call A3M_fnc_buyItem; };
    case 9: { ["B_AssaultPack_khk", "Assault Pack (Khaki)", "backpack"] call A3M_fnc_buyItem; };
    case 10: { ["B_AssaultPack_mcamo", "Assault Pack (MTP)", "backpack"] call A3M_fnc_buyItem; };
    case 11: { ["B_AssaultPack_sgg", "Assault Pack (Sage)", "backpack"] call A3M_fnc_buyItem; };
    case 12: { ["B_Bergen_sgg_Exp", "Bergen (Sage) - Explosives", "backpack"] call A3M_fnc_buyItem; };
    case 13: { ["B_Bergen_sgg", "Bergen (Sage)", "backpack"] call A3M_fnc_buyItem; };
    case 14: { ["B_Carryall_ocamo", "Carryall (Hex)", "backpack"] call A3M_fnc_buyItem; };
    case 15: { ["B_Carryall_oucamo", "Carryall (Urban)", "backpack"] call A3M_fnc_buyItem; };
    case 16: { ["B_Carryall_oucamo_Exp", "Carryall (Urban) - Explosives", "backpack"] call A3M_fnc_buyItem; };
    case 17: { ["B_FieldPack_blk", "Field Pack (Black)", "backpack"] call A3M_fnc_buyItem; };
    case 18: { ["B_FieldPack_blk_DiverTL", "Field Pack (Black) - Diver Team Leader", "backpack"] call A3M_fnc_buyItem; };
    case 19: { ["B_FieldPack_blk_DiverExp", "Field Pack (Black) - Diver Explosives", "backpack"] call A3M_fnc_buyItem; };
    case 20: { ["B_FieldPack_cbr", "Field Pack (Coyote)", "backpack"] call A3M_fnc_buyItem; };
    case 21: { ["B_FieldPack_cbr_AT", "Field Pack (Coyote) - Anti-Tank", "backpack"] call A3M_fnc_buyItem; };
    case 22: { ["B_FieldPack_cbr_Repair", "Field Pack (Coyote) - Engineer", "backpack"] call A3M_fnc_buyItem; };
    case 23: { ["B_FieldPack_ocamo", "Field Pack (Hex)", "backpack"] call A3M_fnc_buyItem; };
    case 24: { ["B_FieldPack_ocamo_Medic", "Field Pack (Hex) - Medic", "backpack"] call A3M_fnc_buyItem; };
    case 25: { ["B_FieldPack_oucamo", "Field Pack (Urban)", "backpack"] call A3M_fnc_buyItem; };
    case 26: { ["B_Kitbag_cbr", "Kitbag (Coyote)", "backpack"] call A3M_fnc_buyItem; };
    case 27: { ["B_Kitbag_mcamo", "Kitbag (MTP)", "backpack"] call A3M_fnc_buyItem; };
    case 28: { ["B_Kitbag_sgg", "Kitbag (Sage)", "backpack"] call A3M_fnc_buyItem; };
    case 29: { ["B_Mk6Mortar_Wpn", "Mk6 Mortar", "backpack"] call A3M_fnc_buyItem; };
};
