switch (TheSelection) do {
	case 191: { ["EF_H_Booniehat_Des", "Booniehat (Desert)", "item"] call A3M_fnc_buyItem; };
	case 192: { ["EF_H_Booniehat_Wdl", "Booniehat (Woodland)", "item"] call A3M_fnc_buyItem; };
	case 193: { ["EF_H_Cap_Navy", "Cap (Navy)", "item"] call A3M_fnc_buyItem; };
	case 194: { ["EF_H_Cap_Takmyr", "Cap (USS Takmyr)", "item"] call A3M_fnc_buyItem; };
	case 195: { ["EF_H_HelmetB_light_black_slick", "Light Combat Helmet (Black, Slick)", "item"] call A3M_fnc_buyItem; };
	case 196: { ["EF_H_HelmetB_light_desert_slick", "Light Combat Helmet (Desert, Slick)", "item"] call A3M_fnc_buyItem; };
	case 197: { ["EF_H_HelmetB_light_grass_slick", "Light Combat Helmet (Grass, Slick)", "item"] call A3M_fnc_buyItem; };
	case 198: { ["EF_H_HelmetB_light_sand_slick", "Light Combat Helmet (Sand, Slick)", "item"] call A3M_fnc_buyItem; };
	case 199: { ["EF_H_HelmetB_light_slick", "Light Combat Helmet (Slick)", "item"] call A3M_fnc_buyItem; };
	case 200: { ["EF_H_HelmetB_light_tna_slick", "Light Combat Helmet (Tropic, Slick)", "item"] call A3M_fnc_buyItem; };
	case 201: { ["EF_H_HelmetB_light_wdl_slick", "Light Combat Helmet (Woodland, Slick)", "item"] call A3M_fnc_buyItem; };
	case 202: { ["EF_H_MCH", "Marine Combat Helmet", "item"] call A3M_fnc_buyItem; };
	case 203: { ["EF_H_MCH_Basic", "Marine Combat Helmet (Basic)", "item"] call A3M_fnc_buyItem; };
	case 204: { ["EF_H_MCH_BasicNet_Black", "Marine Combat Helmet (Basic, Black)", "item"] call A3M_fnc_buyItem; };
	case 205: { ["EF_H_MCH_BasicNet_Coy", "Marine Combat Helmet (Basic, Coyote Brown)", "item"] call A3M_fnc_buyItem; };
	case 206: { ["EF_H_MCH_BasicNet_Des", "Marine Combat Helmet (Basic, Desert)", "item"] call A3M_fnc_buyItem; };
	case 207: { ["EF_H_MCH_BasicNet_Olive", "Marine Combat Helmet (Basic, Olive)", "item"] call A3M_fnc_buyItem; };
	case 208: { ["EF_H_MCH_BasicNet_Wdl", "Marine Combat Helmet (Basic, Woodland)", "item"] call A3M_fnc_buyItem; };
	case 209: { ["EF_H_MCH_Full", "Marine Combat Helmet (Full)", "item"] call A3M_fnc_buyItem; };
	case 210: { ["EF_H_MCH_FullCamo_Black", "Marine Combat Helmet (Full, Black)", "item"] call A3M_fnc_buyItem; };
	case 211: { ["EF_H_MCH_FullCamo_Coy", "Marine Combat Helmet (Full, Coyote Brown)", "item"] call A3M_fnc_buyItem; };
	case 212: { ["EF_H_MCH_FullCamo_Des", "Marine Combat Helmet (Full, Desert)", "item"] call A3M_fnc_buyItem; };
	case 213: { ["EF_H_MCH_FullCamo_Olive", "Marine Combat Helmet (Full, Olive)", "item"] call A3M_fnc_buyItem; };
	case 214: { ["EF_H_MCH_FullCamo_Wdl", "Marine Combat Helmet (Full, Woodland)", "item"] call A3M_fnc_buyItem; };
	case 215: { ["EF_H_Protecta", "Protecta Headset", "item"] call A3M_fnc_buyItem; };
	case 216: { ["EF_H_UtilityCap_Des", "Marine Utility Cap (Desert)", "item"] call A3M_fnc_buyItem; };
	case 217: { ["EF_H_UtilityCap_Wdl", "Marine Utility Cap (Woodland)", "item"] call A3M_fnc_buyItem; };
};
