switch (TheSelection) do {
    case 33: { ["EF_V_CCR_Rifleman_Black", "Commando Chest Rig (Black, Rifleman)", "item"] call A3M_fnc_buyItem; };
    case 34: { ["EF_V_CCR_Scout_Black", "Commando Chest Rig (Black, Scout)", "item"] call A3M_fnc_buyItem; };
    case 35: { ["EF_V_CCR_Support_Black", "Commando Chest Rig (Black, Support)", "item"] call A3M_fnc_buyItem; };
    case 36: { ["EF_V_CCR_TL_Black", "Commando Chest Rig (Black, Team Leader)", "item"] call A3M_fnc_buyItem; };
    case 37: { ["EF_V_CCR_Rifleman_Coy", "Commando Chest Rig (Coyote Brown, Rifleman)", "item"] call A3M_fnc_buyItem; };
    case 38: { ["EF_V_CCR_Scout_Coy", "Commando Chest Rig (Coyote Brown, Scout)", "item"] call A3M_fnc_buyItem; };
    case 39: { ["EF_V_CCR_Support_Coy", "Commando Chest Rig (Coyote Brown, Support)", "item"] call A3M_fnc_buyItem; };
    case 40: { ["EF_V_CCR_TL_Coy", "Commando Chest Rig (Coyote Brown, Team Leader)", "item"] call A3M_fnc_buyItem; };
    case 41: { ["EF_V_CCR_Rifleman_Olive", "Commando Chest Rig (Olive, Rifleman)", "item"] call A3M_fnc_buyItem; };
    case 42: { ["EF_V_CCR_Scout_Olive", "Commando Chest Rig (Olive, Scout)", "item"] call A3M_fnc_buyItem; };
    case 43: { ["EF_V_CCR_Support_Olive", "Commando Chest Rig (Olive, Support)", "item"] call A3M_fnc_buyItem; };
    case 44: { ["EF_V_CCR_TL_Olive", "Commando Chest Rig (Olive, Team Leader)", "item"] call A3M_fnc_buyItem; };
    case 45: { ["EF_V_AAV_Black", "Amphibious Assault Vest (Black)", "item"] call A3M_fnc_buyItem; };
    case 46: { ["EF_V_AAV_Diver_Black", "Amphibious Assault Vest (Black, Diver)", "item"] call A3M_fnc_buyItem; };
    case 47: { ["EF_V_AAV_Diver_NoReb_Black", "Amphibious Assault Vest (Black, Diver, No Rebreather)", "item"] call A3M_fnc_buyItem; };
    case 48: { ["EF_V_AAV_Rifleman_Black", "Amphibious Assault Vest (Black, Rifleman)", "item"] call A3M_fnc_buyItem; };
    case 49: { ["EF_V_AAV_Sailor_Black", "Amphibious Assault Vest (Black, Sailor)", "item"] call A3M_fnc_buyItem; };
    case 50: { ["EF_V_AAV_Scout_Black", "Amphibious Assault Vest (Black, Scout)", "item"] call A3M_fnc_buyItem; };
    case 51: { ["EF_V_AAV_Support_Black", "Amphibious Assault Vest (Black, Support)", "item"] call A3M_fnc_buyItem; };
    case 52: { ["EF_V_AAV_TL_Black", "Amphibious Assault Vest (Black, Team Leader)", "item"] call A3M_fnc_buyItem; };
    case 53: { ["EF_V_AAV_Coy", "Amphibious Assault Vest (Coyote Brown)", "item"] call A3M_fnc_buyItem; };
    case 54: { ["EF_V_AAV_Diver_Coy", "Amphibious Assault Vest (Coyote Brown, Diver)", "item"] call A3M_fnc_buyItem; };
    case 55: { ["EF_V_AAV_Diver_NoReb_Coy", "Amphibious Assault Vest (Coyote Brown, Diver, No Rebreather)", "item"] call A3M_fnc_buyItem; };
    case 56: { ["EF_V_AAV_Rifleman_Coy", "Amphibious Assault Vest (Coyote Brown, Rifleman)", "item"] call A3M_fnc_buyItem; };
    case 57: { ["EF_V_AAV_Sailor_Coy", "Amphibious Assault Vest (Coyote Brown, Sailor)", "item"] call A3M_fnc_buyItem; };
    case 58: { ["EF_V_AAV_Scout_Coy", "Amphibious Assault Vest (Coyote Brown, Scout)", "item"] call A3M_fnc_buyItem; };
    case 59: { ["EF_V_AAV_Support_Coy", "Amphibious Assault Vest (Coyote Brown, Support)", "item"] call A3M_fnc_buyItem; };
    case 60: { ["EF_V_AAV_TL_Coy", "Amphibious Assault Vest (Coyote Brown, Team Leader)", "item"] call A3M_fnc_buyItem; };
    case 61: { ["EF_V_AAV_Olive", "Amphibious Assault Vest (Olive)", "item"] call A3M_fnc_buyItem; };
    case 62: { ["EF_V_AAV_Diver_Olive", "Amphibious Assault Vest (Olive, Diver)", "item"] call A3M_fnc_buyItem; };
    case 63: { ["EF_V_AAV_Diver_NoReb_Olive", "Amphibious Assault Vest (Olive, Diver, No Rebreather)", "item"] call A3M_fnc_buyItem; };
    case 64: { ["EF_V_AAV_Rifleman_Olive", "Amphibious Assault Vest (Olive, Rifleman)", "item"] call A3M_fnc_buyItem; };
    case 65: { ["EF_V_AAV_Sailor_Olive", "Amphibious Assault Vest (Olive, Sailor)", "item"] call A3M_fnc_buyItem; };
    case 66: { ["EF_V_AAV_Scout_Olive", "Amphibious Assault Vest (Olive, Scout)", "item"] call A3M_fnc_buyItem; };
    case 67: { ["EF_V_AAV_Support_Olive", "Amphibious Assault Vest (Olive, Support)", "item"] call A3M_fnc_buyItem; };
    case 68: { ["EF_V_AAV_TL_Olive", "Amphibious Assault Vest (Olive, Team Leader)", "item"] call A3M_fnc_buyItem; };
};
