switch (TheSelection) do {
    case 25 : {["EF_smg_Diplomat", "Diplomat 9mm", "weapon"] call A3M_fnc_buyItem; };
    case 26 : {["EF_smg_Diplomat_Coy", "Diplomat 9mm (Coyote)", "weapon"] call A3M_fnc_buyItem; };
    case 27 : {["EF_smg_Diplomat_Ghex", "Diplomat 9mm (Green Hex)", "weapon"] call A3M_fnc_buyItem; };
    case 28 : {["EF_smg_Diplomat_hex", "Diplomat 9mm (Hex)", "weapon"] call A3M_fnc_buyItem; };
    case 29 : {["ef_arifle_mx_gl_coy", "MX 3GL 6.5mm (Coyote)", "weapon"] call A3M_fnc_buyItem; };
    case 30 : {["ef_arifle_mx_coy", "MX 6.5mm (Coyote)", "weapon"] call A3M_fnc_buyItem; };
    case 31 : {["ef_arifle_mx_sw_coy", "MX SW 6.5mm (Coyote)", "weapon"] call A3M_fnc_buyItem; };
    case 32 : {["ef_arifle_mxar_gl", "MXAR 3GL 6.5mm", "weapon"] call A3M_fnc_buyItem; };
    case 33 : {["ef_arifle_mxar_coy", "MXAR 6.5mm (Coyote)", "weapon"] call A3M_fnc_buyItem; };
    case 34 : {["ef_arifle_mxar_gl_black", "MXAR 3GL 6.5mm (Black)", "weapon"] call A3M_fnc_buyItem; };
    case 35 : {["ef_arifle_mxar_gl_coy", "MXAR 3GL 6.5mm (Coyote)", "weapon"] call A3M_fnc_buyItem; };
    case 36 : {["ef_arifle_mxar_gl_khk", "MXAR 3GL 6.5mm (Khaki)", "weapon"] call A3M_fnc_buyItem; };
    case 37 : {["ef_arifle_mxar", "MXAR 6.5mm", "weapon"] call A3M_fnc_buyItem; };
    case 38 : {["ef_arifle_mxar_black", "MXAR 6.5mm (Black)", "weapon"] call A3M_fnc_buyItem; };
    case 39 : {["ef_arifle_mxar_coy", "MXAR 6.5mm (Coyote)", "weapon"] call A3M_fnc_buyItem; };
    case 40 : {["ef_arifle_mxar_khk", "MXAR 6.5mm (Khaki)", "weapon"] call A3M_fnc_buyItem; };
    case 41 : {["ef_arifle_mxc_coy", "MXC 6.5mm (Coyote)", "weapon"] call A3M_fnc_buyItem; };
    case 42 : {["ef_arifle_mxm_coy", "MXM 6.5mm (Coyote)", "weapon"] call A3M_fnc_buyItem; };
};
