switch (TheSelection) do {
    case 0: { ["Laserdesignator", "Laser Designator", "item"] call A3M_fnc_buyItem; };
    case 1: { ["NVGoggles", "NV Goggles (Gen3, Brown)", "item"] call A3M_fnc_buyItem; };
    case 2: { ["NVGoggles_OPFOR", "NV Goggles (Gen3, Black)", "item"] call A3M_fnc_buyItem; };
    case 3: { ["NVGoggles_INDEP", "NV Goggles (Gen3, Green)", "item"] call A3M_fnc_buyItem; };
    case 4: { ["NVGoggles_tna_F", "NV Goggles (Gen3, Tropic)", "item"] call A3M_fnc_buyItem; };
    case 5: { ["Rangefinder", "U.S. Military Range Finder", "item"] call A3M_fnc_buyItem; };
    case 6: { ["acc_flashlight", "Tactical Flashlight", "item"] call A3M_fnc_buyItem; };
    case 7: { ["acc_pointer_IR", "Infrared Laser Pointer", "item"] call A3M_fnc_buyItem; };
    case 8: { ["I_UAVTerminal", "UAV Control Interface", "item"] call A3M_fnc_buyItem; };
    case 9: { ["ItemGPS", "Outdoorsman GPS Device", "item"] call A3M_fnc_buyItem; };
    case 10: { ["ItemRadio", "Cobra Radio", "item"] call A3M_fnc_buyItem; };
    case 11: { ["ItemWatch", "Casio Survival Watch", "item"] call A3M_fnc_buyItem; };
    case 12: { ["MineDetector", "U.S. Army Mine Detection Device", "item"] call A3M_fnc_buyItem; };
    case 13: { ["Laserbatteries", "Duracell Batteries", "item"] call A3M_fnc_buyItem; };
    case 14: { ["O_NVGoggles_ghex_F", "Compact NVG (Green Hex)", "item"] call A3M_fnc_buyItem; };
    case 15: { ["O_NVGoggles_hex_F", "Compact NVG (Hex)", "item"] call A3M_fnc_buyItem; };
    case 16: { ["O_NVGoggles_urb_F", "Compact NVG (Urban)", "item"] call A3M_fnc_buyItem; };
    case 17: { ["O_NVGoggles_grn_F", "Compact NVG (Green)", "item"] call A3M_fnc_buyItem; };
    case 18: { ["NVGogglesB_blk_F", "ENVG-II (Black)", "item"] call A3M_fnc_buyItem; };
    case 19: { ["NVGogglesB_grn_F", "ENVG-II (Green)", "item"] call A3M_fnc_buyItem; };
    case 20: { ["NVGogglesB_gry_F", "ENVG-II (Grey)", "item"] call A3M_fnc_buyItem; };
};
