switch (TheSelection) do {
	case 111: { ["EF_H_Booniehat_Des", "Booniehat (Desert)", "deliveries"] call A3M_fnc_buyItem; };
	case 112: { ["EF_H_Booniehat_Wdl", "Booniehat (Woodland)", "deliveries"] call A3M_fnc_buyItem; };
	case 113: { ["EF_H_Cap_Navy", "Cap (Navy)", "deliveries"] call A3M_fnc_buyItem; };
	case 114: { ["EF_H_Cap_Takmyr", "Cap (USS Takmyr)", "deliveries"] call A3M_fnc_buyItem; };
	case 115: { ["EF_H_HelmetB_light_black_slick", "Light Combat Helmet (Black, Slick)", "deliveries"] call A3M_fnc_buyItem; };
	case 116: { ["EF_H_HelmetB_light_desert_slick", "Light Combat Helmet (Desert, Slick)", "deliveries"] call A3M_fnc_buyItem; };
	case 117: { ["EF_H_HelmetB_light_grass_slick", "Light Combat Helmet (Grass, Slick)", "deliveries"] call A3M_fnc_buyItem; };
	case 118: { ["EF_H_HelmetB_light_sand_slick", "Light Combat Helmet (Sand, Slick)", "deliveries"] call A3M_fnc_buyItem; };
	case 119: { ["EF_H_HelmetB_light_slick", "Light Combat Helmet (Slick)", "deliveries"] call A3M_fnc_buyItem; };
	case 120: { ["EF_H_HelmetB_light_tna_slick", "Light Combat Helmet (Tropic, Slick)", "deliveries"] call A3M_fnc_buyItem; };
	case 121: { ["EF_H_HelmetB_light_wdl_slick", "Light Combat Helmet (Woodland, Slick)", "deliveries"] call A3M_fnc_buyItem; };
	case 122: { ["EF_H_MCH", "Marine Combat Helmet", "deliveries"] call A3M_fnc_buyItem; };
	case 123: { ["EF_H_MCH_Basic", "Marine Combat Helmet (Basic)", "deliveries"] call A3M_fnc_buyItem; };
	case 124: { ["EF_H_MCH_BasicNet_Black", "Marine Combat Helmet (Basic, Black)", "deliveries"] call A3M_fnc_buyItem; };
	case 125: { ["EF_H_MCH_BasicNet_Coy", "Marine Combat Helmet (Basic, Coyote Brown)", "deliveries"] call A3M_fnc_buyItem; };
	case 126: { ["EF_H_MCH_BasicNet_Des", "Marine Combat Helmet (Basic, Desert)", "deliveries"] call A3M_fnc_buyItem; };
	case 127: { ["EF_H_MCH_BasicNet_Olive", "Marine Combat Helmet (Basic, Olive)", "deliveries"] call A3M_fnc_buyItem; };
	case 128: { ["EF_H_MCH_BasicNet_Wdl", "Marine Combat Helmet (Basic, Woodland)", "deliveries"] call A3M_fnc_buyItem; };
	case 129: { ["EF_H_MCH_Full", "Marine Combat Helmet (Full)", "deliveries"] call A3M_fnc_buyItem; };
	case 130: { ["EF_H_MCH_FullCamo_Black", "Marine Combat Helmet (Full, Black)", "deliveries"] call A3M_fnc_buyItem; };
	case 131: { ["EF_H_MCH_FullCamo_Coy", "Marine Combat Helmet (Full, Coyote Brown)", "deliveries"] call A3M_fnc_buyItem; };
	case 132: { ["EF_H_MCH_FullCamo_Des", "Marine Combat Helmet (Full, Desert)", "deliveries"] call A3M_fnc_buyItem; };
	case 133: { ["EF_H_MCH_FullCamo_Olive", "Marine Combat Helmet (Full, Olive)", "deliveries"] call A3M_fnc_buyItem; };
	case 134: { ["EF_H_MCH_FullCamo_Wdl", "Marine Combat Helmet (Full, Woodland)", "deliveries"] call A3M_fnc_buyItem; };
	case 135: { ["EF_H_Protecta", "Protecta Headset", "deliveries"] call A3M_fnc_buyItem; };
	case 136: { ["EF_H_UtilityCap_Des", "Marine Utility Cap (Desert)", "deliveries"] call A3M_fnc_buyItem; };
	case 137: { ["EF_H_UtilityCap_Wdl", "Marine Utility Cap (Woodland)", "deliveries"] call A3M_fnc_buyItem; };
};
