switch (TheSelection) do {
    case 0: { ["H_Bandanna_camo", "Bandanna (Camo)", "deliveries"] call A3M_fnc_buyItem; };
    case 1: { ["H_Bandanna_cbr", "Bandanna (Coyote)", "deliveries"] call A3M_fnc_buyItem; };
    case 2: { ["H_Bandanna_gry", "Bandanna (Gray)", "deliveries"] call A3M_fnc_buyItem; };
    case 3: { ["H_Bandanna_khk", "Bandanna (Khaki)", "deliveries"] call A3M_fnc_buyItem; };
    case 4: { ["H_Bandanna_khk_hs", "Bandanna (Headset)", "deliveries"] call A3M_fnc_buyItem; };
    case 5: { ["H_Bandanna_mcamo", "Bandanna (MTP)", "deliveries"] call A3M_fnc_buyItem; };
    case 6: { ["H_Bandanna_sgg", "Bandanna (Sage)", "deliveries"] call A3M_fnc_buyItem; };
    case 7: { ["H_Bandanna_surfer", "Bandanna (Surfer)", "deliveries"] call A3M_fnc_buyItem; };
    case 8: { ["H_BandMask_blk", "Bandanna Mask (Black)", "deliveries"] call A3M_fnc_buyItem; };
    case 9: { ["H_BandMask_demon", "Bandanna Mask (Demon)", "deliveries"] call A3M_fnc_buyItem; };
    case 10: { ["H_BandMask_khk", "Bandanna Mask (Khaki)", "deliveries"] call A3M_fnc_buyItem; };
    case 11: { ["H_BandMask_reaper", "Bandanna Mask (Reaper)", "deliveries"] call A3M_fnc_buyItem; };
    case 12: { ["H_Beret_02", "Beret [NATO]", "deliveries"] call A3M_fnc_buyItem; };
    case 13: { ["H_Beret_blk", "Beret (Black)", "deliveries"] call A3M_fnc_buyItem; };
    case 14: { ["H_Beret_blk_POLICE", "Beret (Police)", "deliveries"] call A3M_fnc_buyItem; };
    case 15: { ["H_Beret_brn_SF", "Beret (SAS)", "deliveries"] call A3M_fnc_buyItem; };
    case 16: { ["H_Beret_grn", "Beret (Green)", "deliveries"] call A3M_fnc_buyItem; };
    case 17: { ["H_Beret_grn_SF", "Beret (SF)", "deliveries"] call A3M_fnc_buyItem; };
    case 18: { ["H_Beret_ocamo", "Beret [CSAT", "deliveries"] call A3M_fnc_buyItem; };
    case 19: { ["H_Beret_red", "Beret (Red)", "deliveries"] call A3M_fnc_buyItem; };
    case 20: { ["H_Booniehat_dgtl", "Booniehat [AAF]", "deliveries"] call A3M_fnc_buyItem; };
    case 21: { ["H_Booniehat_dirty", "Booniehat (Dirty)", "deliveries"] call A3M_fnc_buyItem; };
    case 22: { ["H_Booniehat_grn", "Booniehat (Green)", "deliveries"] call A3M_fnc_buyItem; };
    case 23: { ["H_Booniehat_indp", "Booniehat (Khaki)", "deliveries"] call A3M_fnc_buyItem; };
    case 24: { ["H_Booniehat_khk", "Booniehat (Hex)", "deliveries"] call A3M_fnc_buyItem; };
    case 25: { ["H_Booniehat_khk_hs", "Booniehat (Headset", "deliveries"] call A3M_fnc_buyItem; };
    case 26: { ["H_Booniehat_mcamo", "Booniehat (MTP)", "deliveries"] call A3M_fnc_buyItem; };
    case 27: { ["H_Booniehat_tan", "Booniehat (Tan)", "deliveries"] call A3M_fnc_buyItem; };
    case 28: { ["H_Cap_blk", "Cap (Black)", "deliveries"] call A3M_fnc_buyItem; };
    case 29: { ["H_Cap_blk_CMMG", "Cap (CMMG)", "deliveries"] call A3M_fnc_buyItem; };
    case 30: { ["H_Cap_blk_ION", "Cap (ION)", "deliveries"] call A3M_fnc_buyItem; };
    case 31: { ["H_Cap_blk_Raven", "Cap (Raven Security)", "deliveries"] call A3M_fnc_buyItem; };
    case 32: { ["H_Cap_blu", "Cap (Blue)", "deliveries"] call A3M_fnc_buyItem; };
    case 33: { ["H_Cap_brn_SPECOPS", "Cap (SPECOPS)", "deliveries"] call A3M_fnc_buyItem; };
    case 34: { ["H_Cap_grn", "Cap (Green)", "deliveries"] call A3M_fnc_buyItem; };
    case 35: { ["H_Cap_grn_BI", "Cap (BI)", "deliveries"] call A3M_fnc_buyItem; };
    case 36: { ["H_Cap_headphones", "Rangemaster Cap", "deliveries"] call A3M_fnc_buyItem; };
    case 37: { ["H_Cap_khaki_specops_UK", "Cap (SAS", "deliveries"] call A3M_fnc_buyItem; };
    case 38: { ["H_Cap_oli", "Cap (Green)", "deliveries"] call A3M_fnc_buyItem; };
    case 39: { ["H_Cap_oli_hs", "Cap (Olive, Headset)", "deliveries"] call A3M_fnc_buyItem; };
    case 40: { ["H_Cap_red", "Cap (Red)", "deliveries"] call A3M_fnc_buyItem; };
    case 41: { ["H_Cap_tan", "Cap (Tan)", "deliveries"] call A3M_fnc_buyItem; };
    case 42: { ["H_Cap_tan_specops_US", "Cap (SF)", "deliveries"] call A3M_fnc_buyItem; };
    case 43: { ["H_CrewHelmetHeli_B", "Heli Crew Helmet [NATO]", "deliveries"] call A3M_fnc_buyItem; };
    case 44: { ["H_CrewHelmetHeli_I", "Heli Crew Helmet [AAF]", "deliveries"] call A3M_fnc_buyItem; };
    case 45: { ["H_CrewHelmetHeli_O", "Heli Crew Helmet [CSAT]", "deliveries"] call A3M_fnc_buyItem; };
    case 46: { ["H_Hat_blue", "Hat (Blue)", "deliveries"] call A3M_fnc_buyItem; };
    case 47: { ["H_Hat_brown", "Hat (Brown)", "deliveries"] call A3M_fnc_buyItem; };
    case 48: { ["H_Hat_camo", "Hat (Camo", "deliveries"] call A3M_fnc_buyItem; };
    case 49: { ["H_Hat_checker", "Hat (Checker)", "deliveries"] call A3M_fnc_buyItem; };
    case 50: { ["H_Hat_grey", "Hat (Gray)", "deliveries"] call A3M_fnc_buyItem; };
    case 51: { ["H_Hat_tan", "Hat (Tan)", "deliveries"] call A3M_fnc_buyItem; };
    case 52: { ["H_Helmet_Kerry", "Combat Helmet (Camo)", "deliveries"] call A3M_fnc_buyItem; };
    case 53: { ["H_HelmetB", "ECH", "deliveries"] call A3M_fnc_buyItem; };
    case 54: { ["H_HelmetB_black", "ECH (Black)", "deliveries"] call A3M_fnc_buyItem; };
    case 55: { ["H_HelmetB_camo", "ECH (Camo)", "deliveries"] call A3M_fnc_buyItem; };
    case 56: { ["H_HelmetB_desert", "ECH (Desert)", "deliveries"] call A3M_fnc_buyItem; };
    case 57: { ["H_HelmetB_grass", "ECH (Grass)", "deliveries"] call A3M_fnc_buyItem; };
    case 58: { ["H_HelmetB_light", "ECH (Light)", "deliveries"] call A3M_fnc_buyItem; };
    case 59: { ["H_HelmetB_light_black", "ECH (Light, Black)", "deliveries"] call A3M_fnc_buyItem; };
    case 60: { ["H_HelmetB_light_desert", "ECH (Light, Desert)", "deliveries"] call A3M_fnc_buyItem; };
    case 61: { ["H_HelmetB_light_grass", "ECH (Light, Grass)", "deliveries"] call A3M_fnc_buyItem; };
    case 62: { ["H_HelmetB_light_sand", "ECH (Light, Sand)", "deliveries"] call A3M_fnc_buyItem; };
    case 63: { ["H_HelmetB_light_snakeskin", "ECH (Light, Snakeskin)", "deliveries"] call A3M_fnc_buyItem; };
    case 64: { ["H_HelmetB_paint", "ECH (Spraypaint)", "deliveries"] call A3M_fnc_buyItem; };
    case 65: { ["H_HelmetB_plain_blk", "Combat Helmet (Black)", "deliveries"] call A3M_fnc_buyItem; };
    case 66: { ["H_HelmetB_plain_mcamo", "Combat Helmet (Camo)", "deliveries"] call A3M_fnc_buyItem; };
    case 67: { ["H_HelmetB_sand", "ECH (Sand)", "deliveries"] call A3M_fnc_buyItem; };
    case 68: { ["H_HelmetB_snakeskin", "ECH (Snakeskin)", "deliveries"] call A3M_fnc_buyItem; };
    case 69: { ["H_HelmetCrew_B", "Crew Helmet", "deliveries"] call A3M_fnc_buyItem; };
    case 70: { ["H_HelmetCrew_I", "Crew Helmet [AAF]", "deliveries"] call A3M_fnc_buyItem; };
    case 71: { ["H_HelmetCrew_O", "Crew Helmet [CSAT]", "deliveries"] call A3M_fnc_buyItem; };
    case 72: { ["H_HelmetIA", "MICH", "deliveries"] call A3M_fnc_buyItem; };
    case 73: { ["H_HelmetIA_camo", "MICH2 (Camo)", "deliveries"] call A3M_fnc_buyItem; };
    case 74: { ["H_HelmetIA_net", "MICH (Camo)", "deliveries"] call A3M_fnc_buyItem; };
    case 75: { ["H_HelmetLeaderO_ocamo", "Defender Helmet (Hex)", "deliveries"] call A3M_fnc_buyItem; };
    case 76: { ["H_HelmetLeaderO_oucamo", "Defender Helmet (Urban)", "deliveries"] call A3M_fnc_buyItem; };
    case 77: { ["H_HelmetO_ocamo", "Protector Helmet (Hex)", "deliveries"] call A3M_fnc_buyItem; };
    case 78: { ["H_HelmetO_oucamo", "Protector Helmet (Urban)", "deliveries"] call A3M_fnc_buyItem; };
    case 79: { ["H_HelmetSpecB", "SF Helmet", "deliveries"] call A3M_fnc_buyItem; };
    case 80: { ["H_HelmetSpecB_blk", "SF Helmet (Black)", "deliveries"] call A3M_fnc_buyItem; };
    case 81: { ["H_HelmetSpecB_paint1", "SF Helmet (Light paint)", "deliveries"] call A3M_fnc_buyItem; };
    case 82: { ["H_HelmetSpecB_paint2", "SF Helmet (Dark paint)", "deliveries"] call A3M_fnc_buyItem; };
    case 83: { ["H_HelmetSpecO_blk", "Assassin Helmet (Black", "deliveries"] call A3M_fnc_buyItem; };
    case 84: { ["H_HelmetSpecO_ocamo", "Assassin Helmet (Hex)", "deliveries"] call A3M_fnc_buyItem; };
    case 85: { ["H_MilCap_blue", "Blue Cap", "deliveries"] call A3M_fnc_buyItem; };
    case 86: { ["H_MilCap_dgtl", "Military Cap [AAF]", "deliveries"] call A3M_fnc_buyItem; };
    case 87: { ["H_MilCap_gry", "Military Cap (Gray)", "deliveries"] call A3M_fnc_buyItem; };
    case 88: { ["H_MilCap_mcamo", "Military Cap (MTP)", "deliveries"] call A3M_fnc_buyItem; };
    case 89: { ["H_MilCap_ocamo", "Military Cap (Hex)", "deliveries"] call A3M_fnc_buyItem; };
    case 90: { ["H_MilCap_oucamo", "Military Cap (Urban)", "deliveries"] call A3M_fnc_buyItem; };
    case 91: { ["H_MilCap_rucamo", "Military Cap (Russia)", "deliveries"] call A3M_fnc_buyItem; };
    case 92: { ["H_PilotHelmetFighter_B", "Pilot Helmet [NATO]", "deliveries"] call A3M_fnc_buyItem; };
    case 93: { ["H_PilotHelmetFighter_I", "Pilot Helmet [AAF]", "deliveries"] call A3M_fnc_buyItem; };
    case 94: { ["H_PilotHelmetFighter_O", "Pilot Helmet [CSAT]", "deliveries"] call A3M_fnc_buyItem; };
    case 95: { ["H_PilotHelmetHeli_B", "Heli Pilot Helmet [NATO]", "deliveries"] call A3M_fnc_buyItem; };
    case 96: { ["H_PilotHelmetHeli_I", "Heli Pilot Helmet [AAF]", "deliveries"] call A3M_fnc_buyItem; };
    case 97: { ["H_PilotHelmetHeli_O", "Heli Pilot Helmet [CSAT]", "deliveries"] call A3M_fnc_buyItem; };
    case 98: { ["H_Shemag_khk", "Shemag mask (Khaki)", "deliveries"] call A3M_fnc_buyItem; };
    case 99: { ["H_Shemag_olive", "Shemag (Olive)", "deliveries"] call A3M_fnc_buyItem; };
    case 100: { ["H_Shemag_olive_hs", "Shemag (Olive, Headset)", "deliveries"] call A3M_fnc_buyItem; };
    case 101: { ["H_Shemag_tan", "Shemag mask (Tan)", "deliveries"] call A3M_fnc_buyItem; };
    case 102: { ["H_ShemagOpen_khk", "Shemag (Khaki)", "deliveries"] call A3M_fnc_buyItem; };
    case 103: { ["H_ShemagOpen_tan", "Shemag (Tan)", "deliveries"] call A3M_fnc_buyItem; };
    case 104: { ["H_StrawHat", "Straw Hat", "deliveries"] call A3M_fnc_buyItem; };
    case 105: { ["H_StrawHat_dark", "Straw hat (Dark)", "deliveries"] call A3M_fnc_buyItem; };
    case 106: { ["H_TurbanO_blk", "Black Turban", "deliveries"] call A3M_fnc_buyItem; };
    case 107: { ["H_Watchcap_blk", "Beanie", "deliveries"] call A3M_fnc_buyItem; };
    case 108: { ["H_Watchcap_camo", "Beanie (Camo)", "deliveries"] call A3M_fnc_buyItem; };
    case 109: { ["H_Watchcap_khk", "Beanie (Khaki)", "deliveries"] call A3M_fnc_buyItem; };
    case 110: { ["H_Watchcap_sgg", "Beanie (Sage)", "deliveries"] call A3M_fnc_buyItem; };
};
