switch (TheSelection) do {
    case 0 : {["G_Aviator", "Aviator Glasses", "item"] call A3M_fnc_buyItem; };
    case 1 : {["G_Balaclava_blk", "Balaclava (Black)", "item"] call A3M_fnc_buyItem; };
    case 2 : {["G_Balaclava_BlueStrips", "Balaclava (Blue Stripe)", "item"] call A3M_fnc_buyItem; };
    case 3 : {["G_Balaclava_combat", "Balaclava (Combat Goggles)", "item"] call A3M_fnc_buyItem; };
    case 4 : {["G_Balaclava_Flecktarn", "Balaclava (Flecktarn)", "item"] call A3M_fnc_buyItem; };
    case 5 : {["G_Balaclava_Halloween_01", "Balaclava (Halloween)", "item"] call A3M_fnc_buyItem; };
    case 6 : {["G_Balaclava_lowprofile", "Balaclava (Low Profile Goggles)", "item"] call A3M_fnc_buyItem; };
    case 7 : {["G_Balaclava_oli", "Balaclava (Olive)", "item"] call A3M_fnc_buyItem; };
    case 8 : {["G_Balaclava_Flames1", "Balaclava (Orange Pattern)", "item"] call A3M_fnc_buyItem; };
    case 9 : {["G_Balaclava_Scarecrow_01", "Balaclava (Scarecrow)", "item"] call A3M_fnc_buyItem; };
    case 10 : {["G_Balaclava_Skull1", "Balaclava (Skull)", "item"] call A3M_fnc_buyItem; };
    case 11 : {["G_Balaclava_Tropentarn", "Balaclava (Tropentarn)", "item"] call A3M_fnc_buyItem; };
    case 12 : {["G_Bandana_aviator", "Bandana (Aviator)", "item"] call A3M_fnc_buyItem; };
    case 13 : {["G_Bandana_beast", "Bandana (Beast)", "item"] call A3M_fnc_buyItem; };
    case 14 : {["G_Bandana_blk", "Bandana (Black)", "item"] call A3M_fnc_buyItem; };
    case 15 : {["G_Bandana_BlueFlame1", "Bandana (Blue Flame)", "item"] call A3M_fnc_buyItem; };
    case 16 : {["G_Bandana_BlueFlame2", "Bandana (Blue Flames)", "item"] call A3M_fnc_buyItem; };
    case 17 : {["G_Bandana_CandySkull", "Bandana (Candy Skull)", "item"] call A3M_fnc_buyItem; };
    case 18 : {["G_Bandana_khk", "Bandana (Khaki)", "item"] call A3M_fnc_buyItem; };
    case 19 : {["G_Bandana_oli", "Bandana (Olive)", "item"] call A3M_fnc_buyItem; };
    case 20 : {["G_Bandana_OrangeFlame1", "Bandana (Orange Flames)", "item"] call A3M_fnc_buyItem; };
    case 21 : {["G_Bandana_RedFlame1", "Bandana (Red Flames)", "item"] call A3M_fnc_buyItem; };
    case 22 : {["G_Bandana_shades", "Bandana (Shades)", "item"] call A3M_fnc_buyItem; };
    case 23 : {["G_Bandana_Skull1", "Bandana (Skull)", "item"] call A3M_fnc_buyItem; };
    case 24 : {["G_Bandana_Syndikat1", "Bandana (Skull, Syndikat)", "item"] call A3M_fnc_buyItem; };
    case 25 : {["G_Bandana_Skull2", "Bandana (Skull, Ornamental)", "item"] call A3M_fnc_buyItem; };
    case 26 : {["G_Bandana_sport", "Bandana (Sport)", "item"] call A3M_fnc_buyItem; };
    case 27 : {["G_Bandana_tan", "Bandana (Tan)", "item"] call A3M_fnc_buyItem; };
    case 28 : {["G_Bandana_Vampire_01", "Bandana (Vampire)", "item"] call A3M_fnc_buyItem; };
    case 29 : {["G_Bandana_Syndikat", "Bandana (Syndikat)", "item"] call A3M_fnc_buyItem; };
    case 30 : {["G_Combat", "Combat Goggles", "item"] call A3M_fnc_buyItem; };
    case 31: { ["H_Bandanna_camo", "Bandanna (Camo)", "item"] call A3M_fnc_buyItem; };
    case 32: { ["H_Bandanna_cbr", "Bandanna (Coyote)", "item"] call A3M_fnc_buyItem; };
    case 33: { ["H_Bandanna_gry", "Bandanna (Gray)", "item"] call A3M_fnc_buyItem; };
    case 34: { ["H_Bandanna_khk", "Bandanna (Khaki)", "item"] call A3M_fnc_buyItem; };
    case 35: { ["H_Bandanna_khk_hs", "Bandanna (Headset)", "item"] call A3M_fnc_buyItem; };
    case 36: { ["H_Bandanna_mcamo", "Bandanna (MTP)", "item"] call A3M_fnc_buyItem; };
    case 37: { ["H_Bandanna_sgg", "Bandanna (Sage)", "item"] call A3M_fnc_buyItem; };
    case 38: { ["H_Bandanna_surfer", "Bandanna (Surfer)", "item"] call A3M_fnc_buyItem; };
    case 39: { ["H_BandMask_blk", "Bandanna Mask (Black)", "item"] call A3M_fnc_buyItem; };
    case 40: { ["H_BandMask_demon", "Bandanna Mask (Demon)", "item"] call A3M_fnc_buyItem; };
    case 41: { ["H_BandMask_khk", "Bandanna Mask (Khaki)", "item"] call A3M_fnc_buyItem; };
    case 42: { ["H_BandMask_reaper", "Bandanna Mask (Reaper)", "item"] call A3M_fnc_buyItem; };
    case 43: { ["H_Beret_02", "Beret [NATO]", "item"] call A3M_fnc_buyItem; };
    case 44: { ["H_Beret_blk", "Beret (Black)", "item"] call A3M_fnc_buyItem; };
    case 45: { ["H_Beret_blk_POLICE", "Beret (Police)", "item"] call A3M_fnc_buyItem; };
    case 46: { ["H_Beret_brn_SF", "Beret (SAS)", "item"] call A3M_fnc_buyItem; };
    case 47: { ["H_Beret_grn", "Beret (Green)", "item"] call A3M_fnc_buyItem; };
    case 48: { ["H_Beret_grn_SF", "Beret (SF)", "item"] call A3M_fnc_buyItem; };
    case 49: { ["H_Beret_ocamo", "Beret [CSAT", "item"] call A3M_fnc_buyItem; };
    case 50: { ["H_Beret_red", "Beret (Red)", "item"] call A3M_fnc_buyItem; };
    case 51: { ["H_Booniehat_dgtl", "Booniehat [AAF]", "item"] call A3M_fnc_buyItem; };
    case 52: { ["H_Booniehat_dirty", "Booniehat (Dirty)", "item"] call A3M_fnc_buyItem; };
    case 53: { ["H_Booniehat_grn", "Booniehat (Green)", "item"] call A3M_fnc_buyItem; };
    case 54: { ["H_Booniehat_indp", "Booniehat (Khaki)", "item"] call A3M_fnc_buyItem; };
    case 55: { ["H_Booniehat_khk", "Booniehat (Hex)", "item"] call A3M_fnc_buyItem; };
    case 56: { ["H_Booniehat_khk_hs", "Booniehat (Headset", "item"] call A3M_fnc_buyItem; };
    case 57: { ["H_Booniehat_mcamo", "Booniehat (MTP)", "item"] call A3M_fnc_buyItem; };
    case 58: { ["H_Booniehat_tan", "Booniehat (Tan)", "item"] call A3M_fnc_buyItem; };
    case 59: { ["H_Cap_blk", "Cap (Black)", "item"] call A3M_fnc_buyItem; };
    case 60: { ["H_Cap_blk_CMMG", "Cap (CMMG)", "item"] call A3M_fnc_buyItem; };
    case 61: { ["H_Cap_blk_ION", "Cap (ION)", "item"] call A3M_fnc_buyItem; };
    case 62: { ["H_Cap_blk_Raven", "Cap (Raven Security)", "item"] call A3M_fnc_buyItem; };
    case 63: { ["H_Cap_blu", "Cap (Blue)", "item"] call A3M_fnc_buyItem; };
    case 64: { ["H_Cap_brn_SPECOPS", "Cap (SPECOPS)", "item"] call A3M_fnc_buyItem; };
    case 65: { ["H_Cap_grn", "Cap (Green)", "item"] call A3M_fnc_buyItem; };
    case 66: { ["H_Cap_grn_BI", "Cap (BI)", "item"] call A3M_fnc_buyItem; };
    case 67: { ["H_Cap_headphones", "Rangemaster Cap", "item"] call A3M_fnc_buyItem; };
    case 68: { ["H_Cap_khaki_specops_UK", "Cap (SAS", "item"] call A3M_fnc_buyItem; };
    case 69: { ["H_Cap_oli", "Cap (Green)", "item"] call A3M_fnc_buyItem; };
    case 70: { ["H_Cap_oli_hs", "Cap (Olive, Headset)", "item"] call A3M_fnc_buyItem; };
    case 71: { ["H_Cap_red", "Cap (Red)", "item"] call A3M_fnc_buyItem; };
    case 72: { ["H_Cap_tan", "Cap (Tan)", "item"] call A3M_fnc_buyItem; };
    case 73: { ["H_Cap_tan_specops_US", "Cap (SF)", "item"] call A3M_fnc_buyItem; };
    case 74: { ["H_CrewHelmetHeli_B", "Heli Crew Helmet [NATO]", "item"] call A3M_fnc_buyItem; };
    case 75: { ["H_CrewHelmetHeli_I", "Heli Crew Helmet [AAF]", "item"] call A3M_fnc_buyItem; };
    case 76: { ["H_CrewHelmetHeli_O", "Heli Crew Helmet [CSAT]", "item"] call A3M_fnc_buyItem; };
    case 77: { ["H_Hat_blue", "Hat (Blue)", "item"] call A3M_fnc_buyItem; };
    case 78: { ["H_Hat_brown", "Hat (Brown)", "item"] call A3M_fnc_buyItem; };
    case 79: { ["H_Hat_camo", "Hat (Camo", "item"] call A3M_fnc_buyItem; };
    case 80: { ["H_Hat_checker", "Hat (Checker)", "item"] call A3M_fnc_buyItem; };
    case 81: { ["H_Hat_grey", "Hat (Gray)", "item"] call A3M_fnc_buyItem; };
    case 82: { ["H_Hat_tan", "Hat (Tan)", "item"] call A3M_fnc_buyItem; };
    case 83: { ["H_Helmet_Kerry", "Combat Helmet (Camo)", "item"] call A3M_fnc_buyItem; };
    case 84: { ["H_HelmetB", "ECH", "item"] call A3M_fnc_buyItem; };
    case 85: { ["H_HelmetB_black", "ECH (Black)", "item"] call A3M_fnc_buyItem; };
    case 86: { ["H_HelmetB_camo", "ECH (Camo)", "item"] call A3M_fnc_buyItem; };
    case 87: { ["H_HelmetB_desert", "ECH (Desert)", "item"] call A3M_fnc_buyItem; };
    case 88: { ["H_HelmetB_grass", "ECH (Grass)", "item"] call A3M_fnc_buyItem; };
    case 89: { ["H_HelmetB_light", "ECH (Light)", "item"] call A3M_fnc_buyItem; };
    case 90: { ["H_HelmetB_light_black", "ECH (Light, Black)", "item"] call A3M_fnc_buyItem; };
    case 91: { ["H_HelmetB_light_desert", "ECH (Light, Desert)", "item"] call A3M_fnc_buyItem; };
    case 92: { ["H_HelmetB_light_grass", "ECH (Light, Grass)", "item"] call A3M_fnc_buyItem; };
    case 93: { ["H_HelmetB_light_sand", "ECH (Light, Sand)", "item"] call A3M_fnc_buyItem; };
    case 94: { ["H_HelmetB_light_snakeskin", "ECH (Light, Snakeskin)", "item"] call A3M_fnc_buyItem; };
    case 95: { ["H_HelmetB_paint", "ECH (Spraypaint)", "item"] call A3M_fnc_buyItem; };
    case 96: { ["H_HelmetB_plain_blk", "Combat Helmet (Black)", "item"] call A3M_fnc_buyItem; };
    case 97: { ["H_HelmetB_plain_mcamo", "Combat Helmet (Camo)", "item"] call A3M_fnc_buyItem; };
    case 98: { ["H_HelmetB_sand", "ECH (Sand)", "item"] call A3M_fnc_buyItem; };
    case 99: { ["H_HelmetB_snakeskin", "ECH (Snakeskin)", "item"] call A3M_fnc_buyItem; };
    case 100: { ["H_HelmetCrew_B", "Crew Helmet", "item"] call A3M_fnc_buyItem; };
    case 101: { ["H_HelmetCrew_I", "Crew Helmet [AAF]", "item"] call A3M_fnc_buyItem; };
    case 102: { ["H_HelmetCrew_O", "Crew Helmet [CSAT]", "item"] call A3M_fnc_buyItem; };
    case 103: { ["H_HelmetIA", "MICH", "item"] call A3M_fnc_buyItem; };
    case 104: { ["H_HelmetIA_camo", "MICH2 (Camo)", "item"] call A3M_fnc_buyItem; };
    case 105: { ["H_HelmetIA_net", "MICH (Camo)", "item"] call A3M_fnc_buyItem; };
    case 106: { ["H_HelmetLeaderO_ocamo", "Defender Helmet (Hex)", "item"] call A3M_fnc_buyItem; };
    case 107: { ["H_HelmetLeaderO_oucamo", "Defender Helmet (Urban)", "item"] call A3M_fnc_buyItem; };
    case 108: { ["H_HelmetO_ocamo", "Protector Helmet (Hex)", "item"] call A3M_fnc_buyItem; };
    case 109: { ["H_HelmetO_oucamo", "Protector Helmet (Urban)", "item"] call A3M_fnc_buyItem; };
    case 110: { ["H_HelmetSpecB", "SF Helmet", "item"] call A3M_fnc_buyItem; };
    case 111: { ["H_HelmetSpecB_blk", "SF Helmet (Black)", "item"] call A3M_fnc_buyItem; };
    case 112: { ["H_HelmetSpecB_paint1", "SF Helmet (Light paint)", "item"] call A3M_fnc_buyItem; };
    case 113: { ["H_HelmetSpecB_paint2", "SF Helmet (Dark paint)", "item"] call A3M_fnc_buyItem; };
    case 114: { ["H_HelmetSpecO_blk", "Assassin Helmet (Black", "item"] call A3M_fnc_buyItem; };
    case 115: { ["H_HelmetSpecO_ocamo", "Assassin Helmet (Hex)", "item"] call A3M_fnc_buyItem; };
    case 116: { ["H_MilCap_blue", "Blue Cap", "item"] call A3M_fnc_buyItem; };
    case 117: { ["H_MilCap_dgtl", "Military Cap [AAF]", "item"] call A3M_fnc_buyItem; };
    case 118: { ["H_MilCap_gry", "Military Cap (Gray)", "item"] call A3M_fnc_buyItem; };
    case 119: { ["H_MilCap_mcamo", "Military Cap (MTP)", "item"] call A3M_fnc_buyItem; };
    case 120: { ["H_MilCap_ocamo", "Military Cap (Hex)", "item"] call A3M_fnc_buyItem; };
    case 121: { ["H_MilCap_oucamo", "Military Cap (Urban)", "item"] call A3M_fnc_buyItem; };
    case 122: { ["H_MilCap_rucamo", "Military Cap (Russia)", "item"] call A3M_fnc_buyItem; };
    case 123: { ["H_PilotHelmetFighter_B", "Pilot Helmet [NATO]", "item"] call A3M_fnc_buyItem; };
    case 124: { ["H_PilotHelmetFighter_I", "Pilot Helmet [AAF]", "item"] call A3M_fnc_buyItem; };
    case 125: { ["H_PilotHelmetFighter_O", "Pilot Helmet [CSAT]", "item"] call A3M_fnc_buyItem; };
    case 126: { ["H_PilotHelmetHeli_B", "Heli Pilot Helmet [NATO]", "item"] call A3M_fnc_buyItem; };
    case 127: { ["H_PilotHelmetHeli_I", "Heli Pilot Helmet [AAF]", "item"] call A3M_fnc_buyItem; };
    case 128: { ["H_PilotHelmetHeli_O", "Heli Pilot Helmet [CSAT]", "item"] call A3M_fnc_buyItem; };
    case 129: { ["H_Shemag_khk", "Shemag mask (Khaki)", "item"] call A3M_fnc_buyItem; };
    case 130: { ["H_Shemag_olive", "Shemag (Olive)", "item"] call A3M_fnc_buyItem; };
    case 131: { ["H_Shemag_olive_hs", "Shemag (Olive, Headset)", "item"] call A3M_fnc_buyItem; };
    case 132: { ["H_Shemag_tan", "Shemag mask (Tan)", "item"] call A3M_fnc_buyItem; };
    case 133: { ["H_ShemagOpen_khk", "Shemag (Khaki)", "item"] call A3M_fnc_buyItem; };
    case 134: { ["H_ShemagOpen_tan", "Shemag (Tan)", "item"] call A3M_fnc_buyItem; };
    case 135: { ["H_StrawHat", "Straw Hat", "item"] call A3M_fnc_buyItem; };
    case 136: { ["H_StrawHat_dark", "Straw hat (Dark)", "item"] call A3M_fnc_buyItem; };
    case 137: { ["H_TurbanO_blk", "Black Turban", "item"] call A3M_fnc_buyItem; };
    case 138: { ["H_Watchcap_blk", "Beanie", "item"] call A3M_fnc_buyItem; };
    case 139: { ["H_Watchcap_camo", "Beanie (Camo)", "item"] call A3M_fnc_buyItem; };
    case 140: { ["H_Watchcap_khk", "Beanie (Khaki)", "item"] call A3M_fnc_buyItem; };
    case 141: { ["H_Watchcap_sgg", "Beanie (Sage)", "item"] call A3M_fnc_buyItem; };
    case 142 : {["G_Balaclava_TI_blk_F", "Stealth Balaclava (Black)", "item"] call A3M_fnc_buyItem; };
    case 143 : {["G_Balaclava_TI_G_blk_F", "Stealth Balaclava (Black, Goggles)", "item"] call A3M_fnc_buyItem; };
    case 144 : {["G_Balaclava_TI_tna_F", "Stealth Balaclava (Green)", "item"] call A3M_fnc_buyItem; };
    case 145 : {["G_Balaclava_TI_G_tna_F", "Stealth Balaclava (Green, Goggles)", "item"] call A3M_fnc_buyItem; };
    case 146 : {["G_AirPurifyingRespirator_02_black_F", "APR (Black)", "item"] call A3M_fnc_buyItem; };
    case 147 : {["G_AirPurifyingRespirator_02_olive_F", "APR (Olive)", "item"] call A3M_fnc_buyItem; };
    case 148 : {["G_AirPurifyingRespirator_02_sand_F", "APR (Sand)", "item"] call A3M_fnc_buyItem; };
    case 149 : {["G_AirPurifyingRespirator_01_F", "APR (NATO)", "item"] call A3M_fnc_buyItem; };
    case 150 : {["G_RegulatorMask_F", "Regulator Facepiece", "item"] call A3M_fnc_buyItem; };
    case 151 : {["UBM_Mask_Black_01", "Ballistic Mask (Black)", "item"] call A3M_fnc_buyItem; };
    case 152 : {["UBM_Mask_BlackHex_01", "Ballistic Mask (Black Hex)", "item"] call A3M_fnc_buyItem; };
    case 153 : {["UBM_Mask_Green_01", "Ballistic Mask (Green)", "item"] call A3M_fnc_buyItem; };
    case 154 : {["UBM_Mask_Khaki_01", "Ballistic Mask (Khaki)", "item"] call A3M_fnc_buyItem; };
    case 155 : {["UBM_Mask_M90_01", "Ballistic Mask (M90)", "item"] call A3M_fnc_buyItem; };
    case 156 : {["UBM_Mask_MTP_01", "Ballistic Mask (MTP)", "item"] call A3M_fnc_buyItem; };
    case 157 : {["UBM_Mask_Punisher_01", "Ballistic Mask (Punisher)", "item"] call A3M_fnc_buyItem; };
    case 158 : {["UBM_Mask_UCP_01", "Ballistic Mask (UCP)", "item"] call A3M_fnc_buyItem; };
    case 159 : {["UBM_Mask_WhiteHex_01", "Ballistic Mask (White Hex)", "item"] call A3M_fnc_buyItem; };
    case 160 : {["UBM_Mask_Woodland_01", "Ballistic Mask (Woodland)", "item"] call A3M_fnc_buyItem; };
    case 161 : {["H_Beret_gen_F", "Beret (Gendarmerie)", "item"] call A3M_fnc_buyItem; };
    case 162 : {["H_Beret_CSAT_01_F", "Beret (Red)", "item"] call A3M_fnc_buyItem; };
    case 163 : {["H_Booniehat_tna_F", "Booniehat (Tropic)", "item"] call A3M_fnc_buyItem; };
    case 164 : {["H_HelmetB_tna_F", "Combat Helmet (Tropic)", "item"] call A3M_fnc_buyItem; };
    case 165 : {["H_HelmetB_Enh_tna_F", "Enhanced Combat Helmet (Tropic)", "item"] call A3M_fnc_buyItem; };
    case 166 : {["H_HelmetB_Light_tna_F", "Light Combat Helmet (Tropic)", "item"] call A3M_fnc_buyItem; };
    case 167 : {["H_MilCap_ghex_F", "Military Cap (Green Hex)", "item"] call A3M_fnc_buyItem; };
    case 168 : {["H_MilCap_tna_F", "Military Cap (Tropic)", "item"] call A3M_fnc_buyItem; };
    case 169 : {["H_Helmet_Skate", "Skate Helmet", "item"] call A3M_fnc_buyItem; };
    case 170 : {["H_HelmetHBK_F", "Advanced Modular Helmet (Olive)", "item"] call A3M_fnc_buyItem; };
    case 171 : {["H_HelmetHBK_headset_F", "Advanced Modular Helmet", "item"] call A3M_fnc_buyItem; };
    case 172 : {["H_HelmetHBK_chops_F", "Advanced Modular Helmet (Chops)", "item"] call A3M_fnc_buyItem; };
    case 173 : {["H_HelmetHBK_ear_F", "Advanced Modular Helmet (Ear Protectors)", "item"] call A3M_fnc_buyItem; };
    case 174 : {["H_Beret_EAF_01_F", "Beret (LDF)", "item"] call A3M_fnc_buyItem; };
    case 175 : {["H_Booniehat_mgrn", "Booniehat (Green)", "item"] call A3M_fnc_buyItem; };
    case 176 : {["H_Booniehat_taiga", "Booniehat (Taiga)", "item"] call A3M_fnc_buyItem; };
    case 177 : {["H_Booniehat_wdl", "Booniehat (Woodland)", "item"] call A3M_fnc_buyItem; };
    case 178 : {["H_Booniehat_eaf", "Booniehat (LDF)", "item"] call A3M_fnc_buyItem; };
    case 179 : {["H_HelmetB_plain_edl", "Combat Helmet (Woodland)", "item"] call A3M_fnc_buyItem; };
    case 180 : {["H_Tank_eaf_F", "Crew Helmet (Soft, LDF)", "item"] call A3M_fnc_buyItem; };
    case 181 : {["H_HelmetCrew_I_E", "Crew Helmet (LDF)", "item"] call A3M_fnc_buyItem; };
    case 182 : {["H_HelmetSpecB_wdl", "Enhanced Combat Helmet (Woodland)", "item"] call A3M_fnc_buyItem; };
    case 183 : {["H_CrewHelmetHeli_I_E", "Heli Crew Helmet (LDF)", "item"] call A3M_fnc_buyItem; };
    case 184 : {["H_PilotHelmetHeli_I_E", "Heli Pilot Helmet (LDF)", "item"] call A3M_fnc_buyItem; };
    case 185 : {["H_HelmetB_light_wdl", "Light Combat Helmet (Woodland)", "item"] call A3M_fnc_buyItem; };
    case 186 : {["H_MilCap_grn", "Military Cap (Green)", "item"] call A3M_fnc_buyItem; };
    case 187 : {["H_MilCap_taiga", "Military Cap (Taiga)", "item"] call A3M_fnc_buyItem; };
    case 188 : {["H_MilCap_wdl", "Military Cap (Woodland)", "item"] call A3M_fnc_buyItem; };
    case 189 : {["H_MilCap_eaf", "Military Cap (LDF)", "item"] call A3M_fnc_buyItem; };
    case 190 : {["H_Hat_Tinfoil_F", "Tin Foil Hat", "item"] call A3M_fnc_buyItem; };
};
