switch (TheSelection) do {
    case 0 : { ["optic_Aco", "ACO (Red)", "item"] call A3M_fnc_buyItem; };
    case 1 : { ["optic_ACO_grn", "ACO (Green)", "item"] call A3M_fnc_buyItem; };
    case 2 : { ["optic_ACO_grn_smg", "ACO Mini Pic (Fits SMG) (Green)", "item"] call A3M_fnc_buyItem; };
    case 3 : { ["optic_Aco_smg", "ACO Mini Pic (Fits SMG) (Red)", "item"] call A3M_fnc_buyItem; };
    case 4 : { ["optic_Arco", "ARCO", "item"] call A3M_fnc_buyItem; };
    case 5 : { ["optic_DMS", "DMS", "item"] call A3M_fnc_buyItem; };
    case 6 : { ["optic_Hamr", "RCO", "item"] call A3M_fnc_buyItem; };
    case 7 : { ["optic_Holosight", "Holosight", "item"] call A3M_fnc_buyItem; };
    case 8 : { ["optic_Holosight_smg", "MK17 Holosight SMG", "item"] call A3M_fnc_buyItem; };
    case 9 : { ["optic_LRPS", "LRPS", "item"] call A3M_fnc_buyItem; };
    case 10: { ["optic_MRCO", "MRCO", "item"] call A3M_fnc_buyItem; };
    case 11: { ["optic_MRD", "MRD", "item"] call A3M_fnc_buyItem; };
    case 12: { ["optic_Nightstalker", "Nightstalker", "item"] call A3M_fnc_buyItem; };
    case 13: { ["optic_NVS", "NVS", "item"] call A3M_fnc_buyItem; };
    case 14: { ["optic_SOS", "SOS", "item"] call A3M_fnc_buyItem; };
    case 15: { ["optic_tws", "S", "item"] call A3M_fnc_buyItem; };
    case 16: { ["optic_tws_mg", "TWS MG", "item"] call A3M_fnc_buyItem; };
    case 17: { ["optic_Yorris", "Yorris J2", "item"] call A3M_fnc_buyItem; };
};
