switch (TheSelection) do {
    case 0 : { ["optic_Aco", "ACO (Red)", "deliveries"] call A3M_fnc_buyItem; };
    case 1 : { ["optic_ACO_grn", "ACO (Green)", "deliveries"] call A3M_fnc_buyItem; };
    case 2 : { ["optic_ACO_grn_smg", "ACO Mini Pic (Fits SMG) (Green)", "deliveries"] call A3M_fnc_buyItem; };
    case 3 : { ["optic_Aco_smg", "ACO Mini Pic (Fits SMG) (Red)", "deliveries"] call A3M_fnc_buyItem; };
    case 4 : { ["optic_Arco", "ARCO", "deliveries"] call A3M_fnc_buyItem; };
    case 5 : { ["optic_DMS", "DMS", "deliveries"] call A3M_fnc_buyItem; };
    case 6 : { ["optic_Hamr", "RCO", "deliveries"] call A3M_fnc_buyItem; };
    case 7 : { ["optic_Holosight", "Holosight", "deliveries"] call A3M_fnc_buyItem; };
    case 8 : { ["optic_Holosight_smg", "MK17 Holosight SMG", "deliveries"] call A3M_fnc_buyItem; };
    case 9 : { ["optic_LRPS", "LRPS", "deliveries"] call A3M_fnc_buyItem; };
    case 10: { ["optic_MRCO", "MRCO", "deliveries"] call A3M_fnc_buyItem; };
    case 11: { ["optic_MRD", "MRD", "deliveries"] call A3M_fnc_buyItem; };
    case 12: { ["optic_Nightstalker", "Nightstalker", "deliveries"] call A3M_fnc_buyItem; };
    case 13: { ["optic_NVS", "NVS", "deliveries"] call A3M_fnc_buyItem; };
    case 14: { ["optic_SOS", "SOS", "deliveries"] call A3M_fnc_buyItem; };
    case 15: { ["optic_tws", "S", "deliveries"] call A3M_fnc_buyItem; };
    case 16: { ["optic_tws_mg", "TWS MG", "deliveries"] call A3M_fnc_buyItem; };
    case 17: { ["optic_Yorris", "Yorris J2", "deliveries"] call A3M_fnc_buyItem; };
};
