switch (TheSelection) do {
    case 25: { ["rhs_weap_pkm", "PKM", "weapon"] call A3M_fnc_buyItem; };
    case 26: { ["rhs_weap_ak103", "AK-103", "weapon"] call A3M_fnc_buyItem; };
    case 27: { ["rhs_weap_ak103_npz", "AK-103 (NPZ)", "weapon"] call A3M_fnc_buyItem; };
    case 28: { ["rhs_weap_ak103_1", "AK-103 1", "weapon"] call A3M_fnc_buyItem; };
    case 29: { ["rhs_weap_ak103_2", "AK-103 2", "weapon"] call A3M_fnc_buyItem; };
    case 30: { ["rhs_weap_ak74m", "AK-74M", "weapon"] call A3M_fnc_buyItem; };
    case 31: { ["rhs_weap_ak74m_plummag", "AK-74M (Plum Mag)", "weapon"] call A3M_fnc_buyItem; };
    case 32: { ["rhs_weap_ak74m_npz", "AK-74M (NPZ)", "weapon"] call A3M_fnc_buyItem; };
    case 33: { ["rhs_weap_ak74m_folded", "AK-74M (folded)", "weapon"] call A3M_fnc_buyItem; };
    case 34: { ["rhs_weap_ak74m_camo", "AK-74M (camo)", "weapon"] call A3M_fnc_buyItem; };
    case 35: { ["rhs_weap_ak74m_desert", "AK-74M (desert)", "weapon"] call A3M_fnc_buyItem; };
    case 36: { ["rhs_weap_ak74m_2mag", "AK-74M (2 mag)", "weapon"] call A3M_fnc_buyItem; };
    case 37: { ["rhs_weap_ak74m_2mag_npz", "AK-74M (2 mag/NPZ)", "weapon"] call A3M_fnc_buyItem; };
    case 38: { ["rhs_weap_ak74m_2mag_camo", "AK-74M (2 mag and camo)", "weapon"] call A3M_fnc_buyItem; };
    case 39: { ["rhs_weap_ak74m_gp25", "AK-74M (GP-25 Kostyor)", "weapon"] call A3M_fnc_buyItem; };
    case 40: { ["rhs_weap_ak74m_gp25_npz", "AK-74M (GP-25 Kostyor/NPZ)", "weapon"] call A3M_fnc_buyItem; };
    case 41: { ["rhs_weap_svdp", "SVD-M Dragunov", "weapon"] call A3M_fnc_buyItem; };
    case 42: { ["rhs_weap_svdp_wd", "SVD-M Dragunov (camo)", "weapon"] call A3M_fnc_buyItem; };
    case 43: { ["rhs_weap_svds", "SVD-S Dragunov", "weapon"] call A3M_fnc_buyItem; };
    case 44: { ["rhs_weap_svdp_npz", "SVD-M Dragunov", "weapon"] call A3M_fnc_buyItem; };
    case 45: { ["rhs_weap_svdp_wd_npz", "SVD-M Dragunov (camo)", "weapon"] call A3M_fnc_buyItem; };
    case 46: { ["rhs_weap_svds_npz", "SVD-S Dragunov", "weapon"] call A3M_fnc_buyItem; };
    case 47: { ["rhs_weap_m14ebrri", "Mk14 EBR-RI", "weapon"] call A3M_fnc_buyItem; };
    case 48: { ["rhs_weap_m16a4", "M16A4 RIS", "weapon"] call A3M_fnc_buyItem; };
    case 49: { ["rhs_weap_m16a4_grip", "M16A4 (Grippod)", "weapon"] call A3M_fnc_buyItem; };
    case 50: { ["rhs_weap_m16a4_carryhandle", "M16A4 (Carryhandle)", "weapon"] call A3M_fnc_buyItem; };
    case 51: { ["rhs_weap_m16a4_carryhandle_pmag", "M16A4 (Carryhandle/Pmag)", "weapon"] call A3M_fnc_buyItem; };
    case 52: { ["rhs_weap_m16a4_carryhandle_M203", "M16A4 (Carryhandle/M203)", "weapon"] call A3M_fnc_buyItem; };
    case 53: { ["rhs_weap_XM2010", "M2010 ESR", "weapon"] call A3M_fnc_buyItem; };
    case 54: { ["rhs_weap_XM2010_wd", "M2010 ESR (camo)", "weapon"] call A3M_fnc_buyItem; };
    case 55: { ["rhs_weap_XM2010_d", "M2010 ESR (desert)", "weapon"] call A3M_fnc_buyItem; };
    case 56: { ["rhs_weap_XM2010_sa", "M2010 ESR (semi-arid)", "weapon"] call A3M_fnc_buyItem; };
    case 57: { ["rhs_weap_m240B", "M240B", "weapon"] call A3M_fnc_buyItem; };
    case 58: { ["rhs_weap_m249_pip", "M249 PIP", "weapon"] call A3M_fnc_buyItem; };
    case 59: { ["rhs_weap_M320", "M320 GLM", "weapon"] call A3M_fnc_buyItem; };
    case 60: { ["rhs_weap_m4", "M4 RIS", "weapon"] call A3M_fnc_buyItem; };
    case 61: { ["rhs_weap_m4_grip", "M4 (Grippod)", "weapon"] call A3M_fnc_buyItem; };
    case 62: { ["rhs_weap_m4_grip2", "M4 (AFG)", "weapon"] call A3M_fnc_buyItem; };
    case 63: { ["rhs_weap_m4_bipod", "M4 (Bipod)", "weapon"] call A3M_fnc_buyItem; };
    case 64: { ["rhs_weap_m4_carryhandle", "M4 (Carryhandle)", "weapon"] call A3M_fnc_buyItem; };
    case 65: { ["rhs_weap_m4_carryhandle_pmag", "M4 (Carryhandle/PMAG)", "weapon"] call A3M_fnc_buyItem; };
    case 66: { ["rhs_weap_m4_m203", "M4 (M203)", "weapon"] call A3M_fnc_buyItem; };
    case 67: { ["rhs_weap_m4_m203S", "M4 (M203S)", "weapon"] call A3M_fnc_buyItem; };
    case 67: { ["rhs_weap_m4_m203S", "M4 (M203S)", "weapon"] call A3M_fnc_buyItem; };
    case 68: { ["rhs_m4_m320", "M4 (M320)", "weapon"] call A3M_fnc_buyItem; };
    case 69: { ["rhs_weap_m4a1", "M4A1 RIS", "weapon"] call A3M_fnc_buyItem; };
    case 70: { ["rhs_weap_m4a1_grip", "M4A1 (Grippod)", "weapon"] call A3M_fnc_buyItem; };
    case 71: { ["rhs_weap_m4a1_grip2", "M4A1 (AFG)", "weapon"] call A3M_fnc_buyItem; };
    case 72: { ["rhs_weap_m4a1_bipod", "M4A1 (Bipod)", "weapon"] call A3M_fnc_buyItem; };
    case 73: { ["rhs_weap_m4a1_carryhandle", "M4A1 (Carryhandle)", "weapon"] call A3M_fnc_buyItem; };
    case 74: { ["rhs_weap_m4a1_carryhandle_grip", "M4A1 (Carryhandle/Grippod)", "weapon"] call A3M_fnc_buyItem; };
    case 75: { ["rhs_weap_m4a1_carryhandle_grip2", "M4A1 (Carryhandle/AFG)", "weapon"] call A3M_fnc_buyItem; };
    case 76: { ["rhs_weap_m4a1_carryhandle_bipod", "M4A1 (Carryhandle/Bipod)", "weapon"] call A3M_fnc_buyItem; };
    case 77: { ["rhs_weap_m4a1_m203", "M4A1 (M203)", "weapon"] call A3M_fnc_buyItem; };
    case 78: { ["rhs_weap_m4a1_m203s", "M4A1 (M203S)", "weapon"] call A3M_fnc_buyItem; };
    case 79: { ["rhs_weap_m4a1_carryhandle_m203", "M4A1 (Carryhandle/M203)", "weapon"] call A3M_fnc_buyItem; };
    case 80: { ["rhs_weap_m4a1_carryhandle_m203s", "M4A1 (Carryhandle/M203S)", "weapon"] call A3M_fnc_buyItem; };
    case 81: { ["rhs_m4a1_m320", "M4A1 (M320)", "weapon"] call A3M_fnc_buyItem; };
    case 82: { ["rhs_weap_m4a1_blockII", "M4A1 Block II", "weapon"] call A3M_fnc_buyItem; };
    case 83: { ["rhs_weap_m4a1_blockII_grip2", "M4A1 Block II (AFG", "weapon"] call A3M_fnc_buyItem; };
    case 84: { ["rhs_weap_m4a1_blockII_KAC", "M4A1 Block II (KAC)", "weapon"] call A3M_fnc_buyItem; };
    case 85: { ["rhs_weap_m4a1_blockII_grip2_KAC", "M4A1 Block II (AFG/KAC)", "weapon"] call A3M_fnc_buyItem; };
    case 86: { ["rhs_weap_m4a1_blockII_M203", "M4A1 Block II (M203", "weapon"] call A3M_fnc_buyItem; };
    case 87: { ["rhs_weap_M590_5RD", "M590A1 Short", "weapon"] call A3M_fnc_buyItem; };
    case 88: { ["rhs_weap_M590_8RD", "M590A1 Long", "weapon"] call A3M_fnc_buyItem; };
    case 89: { ["rhs_weap_mk18", "MK18", "weapon"] call A3M_fnc_buyItem; };
    case 90: { ["rhs_weap_mk18_grip2", "MK18 (AFG)", "weapon"] call A3M_fnc_buyItem; };
    case 91: { ["rhs_weap_mk18_KAC", "MK18 (KAC", "weapon"] call A3M_fnc_buyItem; };
    case 92: { ["rhs_weap_mk18_grip2_KAC", "MK18 (AFG/KAC)", "weapon"] call A3M_fnc_buyItem; };
    case 93: { ["rhs_weap_sr25", "SR-25", "weapon"] call A3M_fnc_buyItem; };
    case 94: { ["rhs_weap_sr25_ec", "SR-25 EC", "weapon"] call A3M_fnc_buyItem; };
};
