switch (TheSelection) do {
    case 12: { ["rhs_VOG25", "VOG-25", "magazine"] call A3M_fnc_buyItem; };
    case 13: { ["rhs_VOG25p", "VOG-25P (Bouncing)", "magazine"] call A3M_fnc_buyItem; };
    case 14: { ["rhs_vg40tb", "VOG-25TB (Thermobaric)", "magazine"] call A3M_fnc_buyItem; };
    case 15: { ["rhs_g_vg40sz", "VOG-40SZ (Flashbang", "magazine"] call A3M_fnc_buyItem; };
    case 16: { ["rhs_mag_rgd5", "RGD-5", "magazine"] call A3M_fnc_buyItem; };
    case 17: { ["rhs_mag_fakel", "Fakel", "magazine"] call A3M_fnc_buyItem; };
    case 18: { ["rhs_mag_fakels", "Fakel-S", "magazine"] call A3M_fnc_buyItem; };
    case 19: { ["rhs_mag_zarya2", "Zarya-2", "magazine"] call A3M_fnc_buyItem; };
    case 20: { ["rhs_mag_plamyam", "Plamya-M", "magazine"] call A3M_fnc_buyItem; };
    case 21: { ["rhs_mag_M433_HEDP", "M433", "magazine"] call A3M_fnc_buyItem; };
    case 22: { ["rhs_mag_M4009", "Stun grenade", "magazine"] call A3M_fnc_buyItem; };
    case 23: { ["rhs_mag_m576", "M576 Buckshot", "magazine"] call A3M_fnc_buyItem; };
    case 24: { ["rhs_mag_m67", "M67 Frag Grenade", "magazine"] call A3M_fnc_buyItem; };
    case 25: { ["rhs_mag_mk84", "Mk84 Stun Grenade", "magazine"] call A3M_fnc_buyItem; };
    case 26: { ["rhs_mag_an_m14_th3", "M14/Th3 incendiary", "magazine"] call A3M_fnc_buyItem; };
    case 27: { ["rhs_mag_m7a3_cs", "M7A3 Gas CS", "magazine"] call A3M_fnc_buyItem; };
    case 28: { ["rhs_mag_mk3a2", "M84 Stun Grenade", "magazine"] call A3M_fnc_buyItem; };
    case 29: { ["rhs_mag_m69", "M69 Practice Grenade", "magazine"] call A3M_fnc_buyItem; };
};
