switch (TheSelection) do {
	case 111: { ["H_HelmetAggressor_sb_taiga_RF", "Avenger Helmet (Shape Breaker, Taiga)", "item"] call A3M_fnc_buyItem; };
	case 112: { ["H_HelmetAggressor_sb_geo_RF", "Avenger Helmet (Shape Breaker, Geometric)", "item"] call A3M_fnc_buyItem; };
	case 113: { ["H_HelmetAggressor_sb_hex_RF", "Avenger Helmet (Shape Breaker, Hex)", "item"] call A3M_fnc_buyItem; };
	case 114: { ["H_HelmetAggressor_sb_khaki_RF", "Avenger Helmet (Shape Breaker, Khaki)", "item"] call A3M_fnc_buyItem; };
	case 115: { ["H_HelmetAggressor_sb_mtp_RF", "Avenger Helmet (Shape Breaker, MTP)", "item"] call A3M_fnc_buyItem; };
	case 116: { ["H_HelmetAggressor_sb_tna_RF", "Avenger Helmet (Shape Breaker, Tropic", "item"] call A3M_fnc_buyItem; };
	case 117: { ["H_HelmetAggressor_sb_wdl_RF", "Avenger Helmet (Shape Breaker, Woodland)", "item"] call A3M_fnc_buyItem; };
	case 118: { ["H_HelmetHeavy_Black_RF", "Heavy Combat Helmet (Black)", "item"] call A3M_fnc_buyItem; };
	case 119: { ["H_HelmetHeavy_Simple_Black_RF", "Heavy Combat Helmet (Black, No Visor)", "item"] call A3M_fnc_buyItem; };
	case 120: { ["H_HelmetHeavy_VisorUp_Black_RF", "Heavy Combat Helmet (Black, Visor Up)", "item"] call A3M_fnc_buyItem; };
	case 121: { ["H_HelmetHeavy_GHex_RF", "Heavy Combat Helmet (Green Hex)", "item"] call A3M_fnc_buyItem; };
	case 122: { ["H_HelmetHeavy_Simple_GHex_RF", "Heavy Combat Helmet (Green Hex, No Visor)", "item"] call A3M_fnc_buyItem; };
	case 123: { ["H_HelmetHeavy_VisorUp_GHex_RF", "Heavy Combat Helmet (Green Hex, Visor Up)", "item"] call A3M_fnc_buyItem; };
	case 124: { ["H_HelmetHeavy_Hex_RF", "Heavy Combat Helmet (Hex)", "item"] call A3M_fnc_buyItem; };
	case 125: { ["H_HelmetHeavy_Simple_Hex_RF", "Heavy Combat Helmet (Hex, No Visor)", "item"] call A3M_fnc_buyItem; };
	case 126: { ["H_HelmetHeavy_VisorUp_Hex_RF", "Heavy Combat Helmet (Hex, Visor Up)", "item"] call A3M_fnc_buyItem; };
	case 127: { ["H_HelmetHeavy_Olive_RF", "Heavy Combat Helmet (Olive)", "item"] call A3M_fnc_buyItem; };
	case 128: { ["H_HelmetHeavy_Simple_Olive_RF", "Heavy Combat Helmet (Olive, No Visor)", "item"] call A3M_fnc_buyItem; };
	case 129: { ["H_HelmetHeavy_VisorUp_Olive_RF", "Heavy Combat Helmet (Olive, Visor Up)", "item"] call A3M_fnc_buyItem; };
	case 130: { ["H_HelmetHeavy_Sand_RF", "Heavy Combat Helmet (Sand)", "item"] call A3M_fnc_buyItem; };
	case 131: { ["H_HelmetHeavy_Simple_Sand_RF", "Heavy Combat Helmet (Sand, No Visor)", "item"] call A3M_fnc_buyItem; };
	case 132: { ["H_HelmetHeavy_VisorUp_Sand_RF", "Heavy Combat Helmet (Sand, Visor Up)", "item"] call A3M_fnc_buyItem; };
	case 133: { ["H_HelmetHeavy_White_RF", "Heavy Combat Helmet (White)", "item"] call A3M_fnc_buyItem; };
	case 134: { ["H_HelmetHeavy_Simple_White_RF", "Heavy Combat Helmet (White, No Visor)", "item"] call A3M_fnc_buyItem; };
	case 135: { ["H_HelmetHeavy_VisorUp_White_RF", "Heavy Combat Helmet (White, Visor Up)", "item"] call A3M_fnc_buyItem; };
};
