switch (TheSelection) do {
    case 33: { ["rhsusf_iotv_ucp", "IOTV UCP", "deliveries"] call A3M_fnc_buyItem; };
    case 34: { ["rhsusf_iotv_ucp_grenadier", "IOTV UCP (Grenadier)", "deliveries"] call A3M_fnc_buyItem; };
    case 35: { ["rhsusf_iotv_ucp_medic", "IOTV UCP (Medic)", "deliveries"] call A3M_fnc_buyItem; };
    case 36: { ["rhsusf_iotv_ucp_repair", "IOTV UCP (Repair)", "deliveries"] call A3M_fnc_buyItem; };
    case 37: { ["rhsusf_iotv_ucp_rifleman", "IOTV UCP (Rifleman)", "deliveries"] call A3M_fnc_buyItem; };
    case 38: { ["rhsusf_iotv_ucp_SAW", "IOTV UCP (SAW)", "deliveries"] call A3M_fnc_buyItem; };
    case 39: { ["rhsusf_iotv_ucp_squadleader", "IOTV UCP (Squad Leader)", "deliveries"] call A3M_fnc_buyItem; };
    case 40: { ["rhsusf_iotv_ucp_teamleader", "IOTV UCP (Team leader)", "deliveries"] call A3M_fnc_buyItem; };
    case 41: { ["rhsusf_iotv_ocp", "IOTV OCP", "deliveries"] call A3M_fnc_buyItem; };
    case 42: { ["rhsusf_iotv_ocp_grenadier", "IOTV OCP (Grenadier)", "deliveries"] call A3M_fnc_buyItem; };
    case 43: { ["rhsusf_iotv_ocp_medic", "IOTV OCP (Medic)", "deliveries"] call A3M_fnc_buyItem; };
    case 44: { ["rhsusf_iotv_ocp_repair", "IOTV OCP (Repair)", "deliveries"] call A3M_fnc_buyItem; };
    case 45: { ["rhsusf_iotv_ocp_rifleman", "IOTV OCP (Rifleman)", "deliveries"] call A3M_fnc_buyItem; };
    case 46: { ["rhsusf_iotv_ocp_SAW", "IOTV OCP (SAW)", "deliveries"] call A3M_fnc_buyItem; };
    case 47: { ["rhsusf_iotv_ocp_squadleader", "IOTV OCP (Squad Leader)", "deliveries"] call A3M_fnc_buyItem; };
    case 48: { ["rhsusf_iotv_ocp_teamleader", "IOTV OCP (Team leader)", "deliveries"] call A3M_fnc_buyItem; };
    case 49: { ["rhsusf_spc", "SPC (Coyote)", "deliveries"] call A3M_fnc_buyItem; };
    case 50: { ["rhs_6sh92", "6sh92 Flora", "deliveries"] call A3M_fnc_buyItem; };
    case 51: { ["rhs_6sh92_radio", "6sh92 Flora (Radio)", "deliveries"] call A3M_fnc_buyItem; };
    case 52: { ["rhs_6sh92_vog", "6sh92 Flora (VOG)", "deliveries"] call A3M_fnc_buyItem; };
    case 53: { ["rhs_6sh92_vog_headset", "6sh92 Flora (VOG+Headset)", "deliveries"] call A3M_fnc_buyItem; };
    case 54: { ["rhs_6sh92_headset", "6sh92 Flora (Headset)", "deliveries"] call A3M_fnc_buyItem; };
    case 55: { ["rhs_6sh92_digi", "6sh92 EMR Summer", "deliveries"] call A3M_fnc_buyItem; };
    case 56: { ["rhs_6sh92_digi_radio", "6sh92 EMR Summer (Radio)", "deliveries"] call A3M_fnc_buyItem; };
    case 57: { ["rhs_6sh92_digi_vog", "6sh92 EMR Summer (VOG)", "deliveries"] call A3M_fnc_buyItem; };
    case 58: { ["rhs_6sh92_digi_vog_headset", "6sh92 EMR Summer (VOG+Headset)", "deliveries"] call A3M_fnc_buyItem; };
    case 59: { ["rhs_6sh92_digi_headset", "6sh92 EMR Summer (Headset)", "deliveries"] call A3M_fnc_buyItem; };
};
