switch (TheSelection) do {
    case 18: { ["rhs_acc_1p29", "1P29", "deliveries"] call A3M_fnc_buyItem; };
    case 20: { ["rhs_acc_1pn93_1", "1PN93-1 (Night vision)", "deliveries"] call A3M_fnc_buyItem; };
    case 21: { ["rhs_acc_1pn93_2", "1PN93-2 (Night vision - RPG)", "deliveries"] call A3M_fnc_buyItem; };
    case 22: { ["rhs_acc_ekp1", "EKP-1 Kobra", "deliveries"] call A3M_fnc_buyItem; };
    case 23: { ["rhs_acc_pgo7v", "PGO-7V (RPG optic)", "deliveries"] call A3M_fnc_buyItem; };
    case 24: { ["rhs_acc_pkas", "PK-AS (Reflex)", "deliveries"] call A3M_fnc_buyItem; };
    case 25: { ["rhs_acc_pso1m2", "PSO-1M2 (4x24 tele)", "deliveries"] call A3M_fnc_buyItem; };
    case 26: { ["rhsusf_acc_EOTECH", "EOtech XPS3", "deliveries"] call A3M_fnc_buyItem; };
    case 27: { ["rhsusf_acc_eotech_552", "EOtech M552", "deliveries"] call A3M_fnc_buyItem; };
    case 28: { ["rhsusf_acc_LEUPOLDMK4", "Leupold Mk4 (3.5-10x40mm)", "deliveries"] call A3M_fnc_buyItem; };
    case 29: { ["rhsusf_acc_LEUPOLDMK4_2", "Leupold Mk4 (6.5-20x50mm)", "deliveries"] call A3M_fnc_buyItem; };
    case 30: { ["rhsusf_acc_ELCAN", "M145 MGO Elcan", "deliveries"] call A3M_fnc_buyItem; };
    case 31: { ["rhsusf_acc_ELCAN_PIP", "M145 MGO Elcan (PiP)", "deliveries"] call A3M_fnc_buyItem; };
    case 32: { ["rhsusf_acc_ACOG", "M150 RCO ACOG", "deliveries"] call A3M_fnc_buyItem; };
    case 33: { ["rhsusf_acc_ACOG_PIP", "M150 RCO ACOG (PiP)", "deliveries"] call A3M_fnc_buyItem; };
    case 34: { ["rhsusf_acc_ACOG2", "M150 RCO ACOG (ARD)", "deliveries"] call A3M_fnc_buyItem; };
    case 35: { ["rhsusf_acc_ACOG3", "M150 RCO ACOG (ARD/Lens Cover)", "deliveries"] call A3M_fnc_buyItem; };
    case 36: { ["rhsusf_acc_ACOG_USMC", "AN/PVQ-31", "deliveries"] call A3M_fnc_buyItem; };
    case 37: { ["rhsusf_acc_ACOG2_USMC", "AN/PVQ-31 (ARD)", "deliveries"] call A3M_fnc_buyItem; };
    case 38: { ["rhsusf_acc_ACOG3_USMC", "AN/PVQ-31 (ARD/Lens Cover)", "deliveries"] call A3M_fnc_buyItem; };
    case 39: { ["rhsusf_acc_compm4", "M68 CCO Aimpoint M4", "deliveries"] call A3M_fnc_buyItem; };
};
