switch (TheSelection) do {
	case 14: { ["rhs_vg40op_white", "VOG-40 (White Flare)", "deliveries"] call A3M_fnc_buyItem; };
	case 15: { ["rhs_vg40op_green", "VOG-40 (Green Flare)", "deliveries"] call A3M_fnc_buyItem; };
	case 16: { ["rhs_vg40op_red", "VOG-40 (Red Flare)", "deliveries"] call A3M_fnc_buyItem; };
	case 17: { ["rhs_GRD40_white", "GRD-40 (White Smoke)", "deliveries"] call A3M_fnc_buyItem; };
	case 18: { ["rhs_GRD40_green", "GRD-40 (Green Smoke)", "deliveries"] call A3M_fnc_buyItem; };
	case 19: { ["rhs_GRD40_red", "GRD-40 (Red Smoke)", "deliveries"] call A3M_fnc_buyItem; };
	case 20: { ["rhs_weap_rsp30_white", "RSP (White)", "deliveries"] call A3M_fnc_buyItem; };
	case 21: { ["rhs_weap_rsp30_green", "RSP (Green)", "deliveries"] call A3M_fnc_buyItem; };
	case 22: { ["rhs_weap_rsp30_red", "RSP (Red)", "deliveries"] call A3M_fnc_buyItem; };
	case 23: { ["rhs_mag_M585_white", "M585 (White flare)", "deliveries"] call A3M_fnc_buyItem; };
	case 24: { ["rhs_mag_M661_green", "M661 (Green flare)", "deliveries"] call A3M_fnc_buyItem; };
	case 25: { ["rhs_mag_M662_red", "M662 (Red flare)", "deliveries"] call A3M_fnc_buyItem; };
	case 26: { ["rhs_mag_M713_red", "M713 (Red Smoke)", "deliveries"] call A3M_fnc_buyItem; };
	case 27: { ["rhs_mag_M714_white", "M714 (White Smoke)", "deliveries"] call A3M_fnc_buyItem; };
	case 28: { ["rhs_mag_M715_green", "M715 (Green Smoke)", "deliveries"] call A3M_fnc_buyItem; };
	case 29: { ["rhs_mag_M716_yellow", "M716 (Yellow Smoke)", "deliveries"] call A3M_fnc_buyItem; };
	case 30: { ["rhs_mag_an_m8hc", "M8HC Smoke (white)", "deliveries"] call A3M_fnc_buyItem; };
	case 31: { ["rhs_mag_m18_purple", "M18 Smoke (Purple)", "deliveries"] call A3M_fnc_buyItem; };
	case 32: { ["rhs_mag_m18_green", "M18 Smoke (Green)", "deliveries"] call A3M_fnc_buyItem; };
	case 33: { ["rhs_mag_m18_red", "M18 Smoke (Red", "deliveries"] call A3M_fnc_buyItem; };
	case 34: { ["rhs_mag_m18_yellow", "M18 Smoke (Yellow)", "deliveries"] call A3M_fnc_buyItem; };
	case 35: { ["rhs_mag_rdg2_white", "RGD-2 (white smoke)", "deliveries"] call A3M_fnc_buyItem; };
	case 36: { ["rhs_mag_rdg2_black", "RGD-2 (black smoke)", "deliveries"] call A3M_fnc_buyItem; };
	case 37: { ["rhs_mag_nspn_yellow", "NSP-N (yellow flare)", "deliveries"] call A3M_fnc_buyItem; };
	case 38: { ["rhs_mag_nspn_red", "NSP-N (red flare", "deliveries"] call A3M_fnc_buyItem; };
	case 39: { ["rhs_mag_nspn_green", "NSP-N (green flare)", "deliveries"] call A3M_fnc_buyItem; };
	case 40: { ["rhs_mag_nspd", "NSP-D (red flare)", "deliveries"] call A3M_fnc_buyItem; };
};
