switch (TheSelection) do {
	case 191: { ["H_HelmetAggressor_sb_taiga_RF", "Avenger Helmet (Shape Breaker, Taiga)", "item"] call A3M_fnc_buyItem; };
	case 192: { ["H_HelmetAggressor_sb_geo_RF", "Avenger Helmet (Shape Breaker, Geometric)", "item"] call A3M_fnc_buyItem; };
	case 193: { ["H_HelmetAggressor_sb_hex_RF", "Avenger Helmet (Shape Breaker, Hex)", "item"] call A3M_fnc_buyItem; };
	case 194: { ["H_HelmetAggressor_sb_khaki_RF", "Avenger Helmet (Shape Breaker, Khaki)", "item"] call A3M_fnc_buyItem; };
	case 195: { ["H_HelmetAggressor_sb_mtp_RF", "Avenger Helmet (Shape Breaker, MTP)", "item"] call A3M_fnc_buyItem; };
	case 196: { ["H_HelmetAggressor_sb_tna_RF", "Avenger Helmet (Shape Breaker, Tropic", "item"] call A3M_fnc_buyItem; };
	case 197: { ["H_HelmetAggressor_sb_wdl_RF", "Avenger Helmet (Shape Breaker, Woodland)", "item"] call A3M_fnc_buyItem; };
	case 198: { ["H_HelmetHeavy_Black_RF", "Heavy Combat Helmet (Black)", "item"] call A3M_fnc_buyItem; };
	case 199: { ["H_HelmetHeavy_Simple_Black_RF", "Heavy Combat Helmet (Black, No Visor)", "item"] call A3M_fnc_buyItem; };
	case 200: { ["H_HelmetHeavy_VisorUp_Black_RF", "Heavy Combat Helmet (Black, Visor Up)", "item"] call A3M_fnc_buyItem; };
	case 201: { ["H_HelmetHeavy_GHex_RF", "Heavy Combat Helmet (Green Hex)", "item"] call A3M_fnc_buyItem; };
	case 202: { ["H_HelmetHeavy_Simple_GHex_RF", "Heavy Combat Helmet (Green Hex, No Visor)", "item"] call A3M_fnc_buyItem; };
	case 203: { ["H_HelmetHeavy_VisorUp_GHex_RF", "Heavy Combat Helmet (Green Hex, Visor Up)", "item"] call A3M_fnc_buyItem; };
	case 204: { ["H_HelmetHeavy_Hex_RF", "Heavy Combat Helmet (Hex)", "item"] call A3M_fnc_buyItem; };
	case 205: { ["H_HelmetHeavy_Simple_Hex_RF", "Heavy Combat Helmet (Hex, No Visor)", "item"] call A3M_fnc_buyItem; };
	case 206: { ["H_HelmetHeavy_VisorUp_Hex_RF", "Heavy Combat Helmet (Hex, Visor Up)", "item"] call A3M_fnc_buyItem; };
	case 207: { ["H_HelmetHeavy_Olive_RF", "Heavy Combat Helmet (Olive)", "item"] call A3M_fnc_buyItem; };
	case 208: { ["H_HelmetHeavy_Simple_Olive_RF", "Heavy Combat Helmet (Olive, No Visor)", "item"] call A3M_fnc_buyItem; };
	case 209: { ["H_HelmetHeavy_VisorUp_Olive_RF", "Heavy Combat Helmet (Olive, Visor Up)", "item"] call A3M_fnc_buyItem; };
	case 210: { ["H_HelmetHeavy_Sand_RF", "Heavy Combat Helmet (Sand)", "item"] call A3M_fnc_buyItem; };
	case 211: { ["H_HelmetHeavy_Simple_Sand_RF", "Heavy Combat Helmet (Sand, No Visor)", "item"] call A3M_fnc_buyItem; };
	case 212: { ["H_HelmetHeavy_VisorUp_Sand_RF", "Heavy Combat Helmet (Sand, Visor Up)", "item"] call A3M_fnc_buyItem; };
	case 213: { ["H_HelmetHeavy_White_RF", "Heavy Combat Helmet (White)", "item"] call A3M_fnc_buyItem; };
	case 214: { ["H_HelmetHeavy_Simple_White_RF", "Heavy Combat Helmet (White, No Visor)", "item"] call A3M_fnc_buyItem; };
	case 215: { ["H_HelmetHeavy_VisorUp_White_RF", "Heavy Combat Helmet (White, Visor Up)", "item"] call A3M_fnc_buyItem; };
};
