switch (TheSelection) do {
case 191: { ["rhsusf_ach_bare", "ACH Bare", "item"] call A3M_fnc_buyItem; };
case 192: { ["rhsusf_ach_bare_ess", "ACH Bare W/ ESS", "item"] call A3M_fnc_buyItem; };
case 193: { ["rhsusf_ach_bare_headset", "ACH Bare W/ Headset", "item"] call A3M_fnc_buyItem; };
case 194: { ["rhsusf_ach_bare_headset_ess", "ACH Bare W/ Headset+ESS", "item"] call A3M_fnc_buyItem; };
case 195: { ["rhsusf_ach_bare_tan", "ACH Tan", "item"] call A3M_fnc_buyItem; };
case 196: { ["rhsusf_ach_bare_tan_ess", "ACH Tan W/ ESS", "item"] call A3M_fnc_buyItem; };
case 197: { ["rhsusf_ach_bare_tan_headset", "ACH Tan W/ Headset", "item"] call A3M_fnc_buyItem; };
case 198: { ["rhsusf_ach_bare_tan_headset_ess", "ACH Tan W/ Headset+ESS", "item"] call A3M_fnc_buyItem; };
case 199: { ["rhsusf_ach_bare_wood", "ACH Wood", "item"] call A3M_fnc_buyItem; };
case 200: { ["rhsusf_ach_bare_wood_ess", "ACH Wood W/ ESS", "item"] call A3M_fnc_buyItem; };
case 201: { ["rhsusf_ach_bare_wood_headset", "ACH Wood W/ Headset", "item"] call A3M_fnc_buyItem; };
case 202: { ["rhsusf_ach_bare_wood_headset_ess", "ACH Wood W/ Headset+ESS", "item"] call A3M_fnc_buyItem; };
case 203: { ["rhsusf_ach_bare_des", "ACH Desert", "item"] call A3M_fnc_buyItem; };
case 204: { ["rhsusf_ach_bare_des_ess", "ACH Desert W/ ESS", "item"] call A3M_fnc_buyItem; };
case 205: { ["rhsusf_ach_bare_des_headset", "ACH Desert W/ Headset", "item"] call A3M_fnc_buyItem; };
case 206: { ["rhsusf_ach_bare_des_headset_ess", "ACH Desert W/ Headset+ESS", "item"] call A3M_fnc_buyItem; };
case 207: { ["rhsusf_ach_bare_semi", "ACH Semi-Arid", "item"] call A3M_fnc_buyItem; };
case 208: { ["rhsusf_ach_bare_semi_ess", "ACH Semi-Arid W/ ESS", "item"] call A3M_fnc_buyItem; };
case 209: { ["rhsusf_ach_bare_semi_headset", "ACH Semi-Arid W/ Headset", "item"] call A3M_fnc_buyItem; };
case 210: { ["rhsusf_ach_bare_semi_headset_ess", "ACH Semi-Arid W/ Headset+ESS", "item"] call A3M_fnc_buyItem; };
case 211: { ["rhsusf_ach_helmet_ucp", "ACH UCP", "item"] call A3M_fnc_buyItem; };
case 212: { ["rhsusf_ach_helmet_ess_ucp", "ACH UCP W/ ESS", "item"] call A3M_fnc_buyItem; };
case 213: { ["rhsusf_ach_helmet_headset_ucp", "ACH UCP W/ Headset", "item"] call A3M_fnc_buyItem; };
case 214: { ["rhsusf_ach_helmet_headset_ess_ucp", "ACH UCP W/ Headset+ESS", "item"] call A3M_fnc_buyItem; };
case 215: { ["rhsusf_ach_helmet_ocp", "ACH OCP", "item"] call A3M_fnc_buyItem; };
case 216: { ["rhsusf_ach_helmet_camo_ocp", "ACH OCP Camo", "item"] call A3M_fnc_buyItem; };
case 217: { ["rhsusf_ach_helmet_ess_ocp", "ACH OCP W/ ESS", "item"] call A3M_fnc_buyItem; };
case 218: { ["rhsusf_ach_helmet_headset_ocp", "ACH OCP W/ Headset", "item"] call A3M_fnc_buyItem; };
case 219: { ["rhsusf_ach_helmet_headset_ess_ocp", "ACH OCP W/ Headset+ESS", "item"] call A3M_fnc_buyItem; };
case 220: { ["rhsusf_ach_helmet_m81", "M81", "item"] call A3M_fnc_buyItem; };
case 221: { ["rhsusf_mich_bare", "MICH 2000 Bare (Olive) Clean", "item"] call A3M_fnc_buyItem; };
case 222: { ["rhsusf_mich_bare_headset", "MICH 2000 Bare (Olive) Headset", "item"] call A3M_fnc_buyItem; };
case 223: { ["rhsusf_mich_bare_alt", "MICH 2000 Bare (Olive) Alternative", "item"] call A3M_fnc_buyItem; };
case 224: { ["rhsusf_mich_bare_norotos", "MICH 2000 Bare (Olive) Norotos", "item"] call A3M_fnc_buyItem; };
case 225: { ["rhsusf_mich_bare_norotos_headset", "MICH 2000 Bare (Olive) Norotos / Headset", "item"] call A3M_fnc_buyItem; };
case 226: { ["rhsusf_mich_bare_norotos_alt", "MICH 2000 Bare (Olive) Norotos / Alt", "item"] call A3M_fnc_buyItem; };
case 227: { ["rhsusf_mich_bare_norotos_alt_headset", "MICH 2000 Bare (Olive) Norotos / Alt", "item"] call A3M_fnc_buyItem; };
case 228: { ["rhsusf_mich_bare_norotos_arc", "MICH 2000 Bare (Olive) Norotos / Arc", "item"] call A3M_fnc_buyItem; };
case 229: { ["rhsusf_mich_bare_norotos_arc_headset", "MICH 2000 Bare (Olive) Norotos / Arc / Headset", "item"] call A3M_fnc_buyItem; };
case 230: { ["rhsusf_mich_bare_norotos_arc_alt", "MICH 2000 Bare (Olive) Norotos / Arc / Alt", "item"] call A3M_fnc_buyItem; };
case 231: { ["rhsusf_mich_bare_norotos_arc_alt_headset", "MICH 2000 Bare (Olive) Norotos / Arc / Alt / Headset", "item"] call A3M_fnc_buyItem; };
case 232: { ["rhsusf_mich_bare_tan", "MICH 2000 Bare (Tan) Clean", "item"] call A3M_fnc_buyItem; };
case 233: { ["rhsusf_mich_bare_tan_headset", "MICH 2000 Bare (Tan) Headset", "item"] call A3M_fnc_buyItem; };
case 234: { ["rhsusf_mich_bare_alt_tan", "MICH 2000 Bare (Tan) Alternative", "item"] call A3M_fnc_buyItem; };
case 235: { ["rhsusf_mich_bare_norotos_tan", "MICH 2000 Bare (Tan) Norotos", "item"] call A3M_fnc_buyItem; };
case 236: { ["rhsusf_mich_bare_norotos_tan_headset", "MICH 2000 Bare (Tan) Norotos / Headset", "item"] call A3M_fnc_buyItem; };
case 237: { ["rhsusf_mich_bare_norotos_alt_tan", "MICH 2000 Bare (Tan) Norotos / Alt", "item"] call A3M_fnc_buyItem; };
case 238: { ["rhsusf_mich_bare_norotos_alt_tan_headset", "MICH 2000 Bare (Tan) Norotos / Alt", "item"] call A3M_fnc_buyItem; };
case 239: { ["rhsusf_mich_bare_norotos_arc_tan", "MICH 2000 Bare (Tan) Norotos / Arc", "item"] call A3M_fnc_buyItem; };
case 240: { ["rhsusf_mich_bare_norotos_arc_tan_headset", "MICH 2000 Bare (Tan) Norotos / Arc / Headset", "item"] call A3M_fnc_buyItem; };
case 241: { ["rhsusf_mich_bare_norotos_arc_alt_tan", "MICH 2000 Bare (Tan) Norotos / Arc / Alt", "item"] call A3M_fnc_buyItem; };
case 242: { ["rhsusf_mich_bare_norotos_arc_alt_tan_headset", "MICH 2000 Bare (Tan) Norotos / Arc / Alt / Headset", "item"] call A3M_fnc_buyItem; };
case 243: { ["rhsusf_mich_bare_semi", "MICH 2000 Bare (Semi-Arid) Clean", "item"] call A3M_fnc_buyItem; };
case 244: { ["rhsusf_mich_bare_semi_headset", "MICH 2000 Bare (Semi-Arid) Headset", "item"] call A3M_fnc_buyItem; };
case 245: { ["rhsusf_mich_bare_alt_semi", "MICH 2000 Bare (Semi-Arid) Alternative", "item"] call A3M_fnc_buyItem; };
case 246: { ["rhsusf_mich_bare_norotos_semi", "MICH 2000 Bare (Semi-Arid) Norotos", "item"] call A3M_fnc_buyItem; };
case 247: { ["rhsusf_mich_bare_norotos_semi_headset", "MICH 2000 Bare (Semi-Arid) Norotos / Headset", "item"] call A3M_fnc_buyItem; };
case 248: { ["rhsusf_mich_bare_norotos_alt_semi", "MICH 2000 Bare (Semi-Arid) Norotos / Alternative", "item"] call A3M_fnc_buyItem; };
case 249: { ["rhsusf_mich_bare_norotos_alt_semi_headset", "MICH 2000 Bare (Semi-Arid) Norotos / Alternative", "item"] call A3M_fnc_buyItem; };
case 250: { ["rhsusf_mich_bare_norotos_arc_semi", "MICH 2000 Bare (Semi-Arid) Norotos / Arc", "item"] call A3M_fnc_buyItem; };
case 251: { ["rhsusf_mich_bare_norotos_arc_semi_headset", "MICH 2000 Bare (Semi-Arid) Norotos / Arc / Headset", "item"] call A3M_fnc_buyItem; };
case 252: { ["rhsusf_mich_bare_norotos_arc_alt_semi", "MICH 2000 Bare (Semi-Arid) Norotos / Arc / Alt", "item"] call A3M_fnc_buyItem; };
case 253: { ["rhsusf_mich_bare_norotos_arc_alt_semi_headset", "MICH 2000 Bare (Semi-Arid) Norotos / Arc / Alt / Headset", "item"] call A3M_fnc_buyItem; };
case 254: { ["rhsusf_mich_helmet_marpatwd", "MICH 2000 Bare (MARPAT Woodland) Clean", "item"] call A3M_fnc_buyItem; };
case 255: { ["rhsusf_mich_helmet_marpatwd_headset", "MICH 2000 Bare (MARPAT Woodland) Headset", "item"] call A3M_fnc_buyItem; };
case 256: { ["rhsusf_mich_helmet_marpatwd_alt", "MICH 2000 Bare (MARPAT Woodland) Alt", "item"] call A3M_fnc_buyItem; };
case 257: { ["rhsusf_mich_helmet_marpatwd_alt_headset", "MICH 2000 Bare (MARPAT Woodland) Alt / Headset", "item"] call A3M_fnc_buyItem; };
case 258: { ["rhsusf_mich_helmet_marpatwd_norotos", "MICH 2000 Bare (MARPAT Woodland) Norotos", "item"] call A3M_fnc_buyItem; };
case 259: { ["rhsusf_mich_helmet_marpatwd_norotos_headset", "MICH 2000 Bare (MARPAT Woodland) Norotos / Headset", "item"] call A3M_fnc_buyItem; };
case 260: { ["rhsusf_mich_helmet_marpatwd_norotos_arc", "MICH 2000 Bare (MARPAT Woodland) Norotos / Arc", "item"] call A3M_fnc_buyItem; };
case 261: { ["rhsusf_mich_helmet_marpatwd_norotos_arc_headset", "MICH 2000 Bare (MARPAT Woodland) Norotos / Arc / Headset", "item"] call A3M_fnc_buyItem; };
case 262: { ["rhsusf_mich_helmet_marpatd", "MICH 2000 Bare (MARPAT Desert) Clean", "item"] call A3M_fnc_buyItem; };
case 263: { ["rhsusf_mich_helmet_marpatd_headset", "MICH 2000 Bare (MARPAT Desert) Headset", "item"] call A3M_fnc_buyItem; };
case 264: { ["rhsusf_mich_helmet_marpatd_alt", "MICH 2000 Bare (MARPAT Desert) Alt", "item"] call A3M_fnc_buyItem; };
case 265: { ["rhsusf_mich_helmet_marpatd_alt_headset", "MICH 2000 Bare (MARPAT Desert) Alt / Headset", "item"] call A3M_fnc_buyItem; };
case 266: { ["rhsusf_mich_helmet_marpatd_norotos", "MICH 2000 Bare (MARPAT Desert) Norotos", "item"] call A3M_fnc_buyItem; };
case 267: { ["rhsusf_mich_helmet_marpatd_norotos_headset", "MICH 2000 Bare (MARPAT Desert) Norotos / Headset", "item"] call A3M_fnc_buyItem; };
case 268: { ["rhsusf_mich_helmet_marpatd_norotos_arc", "MICH 2000 Bare (MARPAT Desert) Norotos / Arc", "item"] call A3M_fnc_buyItem; };
case 269: { ["rhsusf_mich_helmet_marpatd_norotos_arc_headset", "MICH 2000 Bare (MARPAT Desert) Norotos / Arc / Headset", "item"] call A3M_fnc_buyItem; };
case 270: { ["rhsusf_opscore_02", "OPS CORE Bare", "item"] call A3M_fnc_buyItem; };
case 271: { ["rhsusf_opscore_01", "OPS CORE Bare (Headset)", "item"] call A3M_fnc_buyItem; };
case 272: { ["rhsusf_opscore_02_tan", "OPS CORE Tan", "item"] call A3M_fnc_buyItem; };
case 273: { ["rhsusf_opscore_01_tan", "OPS CORE Tan (Headset)", "item"] call A3M_fnc_buyItem; };
case 274: { ["rhsusf_opscore_04_ocp", "OPS CORE OCP", "item"] call A3M_fnc_buyItem; };
case 275: { ["rhsusf_opscore_03_ocp", "OPS CORE OCP (Headset)", "item"] call A3M_fnc_buyItem; };
case 276: { ["rhs_Booniehat_ucp", "Boonie Hat UCP", "item"] call A3M_fnc_buyItem; };
case 277: { ["rhs_Booniehat_ocp", "Boonie Hat OCP", "item"] call A3M_fnc_buyItem; };
case 278: { ["rhs_Booniehat_marpatwd", "Boonie Hat MARPAT (Woodland)", "item"] call A3M_fnc_buyItem; };
case 279: { ["rhs_Booniehat_marpatd", "Boonie Hat MARPAT (Desert)", "item"] call A3M_fnc_buyItem; };
case 280: { ["rhs_Booniehat_m81", "M81", "item"] call A3M_fnc_buyItem; };
case 281: { ["rhsusf_Bowman", "Bowman Headset", "item"] call A3M_fnc_buyItem; };
case 282: { ["rhsusf_bowman_cap", "Bowman Headset w/ Cap", "item"] call A3M_fnc_buyItem; };
case 283: { ["rhsusf_patrolcap_ucp", "Patrol Cap (UCP)", "item"] call A3M_fnc_buyItem; };
case 284: { ["rhsusf_patrolcap_ocp", "Patrol Cap (OCP)", "item"] call A3M_fnc_buyItem; };
case 285: { ["rhsusf_cvc_helmet", "Tank Helmet CVC Tan", "item"] call A3M_fnc_buyItem; };
case 286: { ["rhsusf_cvc_ess", "Tank Helmet CVC Tan (ESS)", "item"] call A3M_fnc_buyItem; };
case 287: { ["rhsusf_cvc_green_helmet", "Tank Helmet CVC Green", "item"] call A3M_fnc_buyItem; };
case 288: { ["rhsusf_cvc_green_ess", "Tank Helmet CVC Green (ESS)", "item"] call A3M_fnc_buyItem; };
case 289: { ["PilotHelmetHeli", "Pilot/Crew Helmet HGU-56/P", "item"] call A3M_fnc_buyItem; };
case 290: { ["H_CrewHelmetHeli_B", "Pilot/Crew Helmet HGU-56/P (Mask)", "item"] call A3M_fnc_buyItem; };
case 291: { ["rhs_balaclava", "Balaclava", "item"] call A3M_fnc_buyItem; };
case 292: { ["rhs_scarf", "Scarf", "item"] call A3M_fnc_buyItem; };
case 293: { ["rhs_6b27m_green", "Helmet 6B27M Plain", "item"] call A3M_fnc_buyItem; };
case 294: { ["rhs_6b27m_green_ess", "Helmet 6B27M Plain (Goggles)", "item"] call A3M_fnc_buyItem; };
case 295: { ["rhs_6b27m_green_bala", "Helmet 6B27M Plain (Balaclava)", "item"] call A3M_fnc_buyItem; };
case 296: { ["rhs_6b27m_green_ess_bala", "Helmet 6B27M Plain (Goggles and Balaclava)", "item"] call A3M_fnc_buyItem; };
case 297: { ["rhs_6b27m", "Helmet 6B27M Flora", "item"] call A3M_fnc_buyItem; };
case 298: { ["rhs_6b27m_ess", "Helmet 6B27M Flora (Googles)", "item"] call A3M_fnc_buyItem; };
case 299: { ["rhs_6b27m_bala", "Helmet 6B27M Flora (Balaclava)", "item"] call A3M_fnc_buyItem; };
case 300: { ["rhs_6b27m_ess_bala", "Helmet 6B27M Flora (Goggles and Balaclava)", "item"] call A3M_fnc_buyItem; };
case 301: { ["rhs_6b27m_digi", "Helmet 6B27M EMR-Summer", "item"] call A3M_fnc_buyItem; };
case 302: { ["rhs_6b27m_digi_bala", "Helmet 6B27M EMR-Summer (Balaclava)", "item"] call A3M_fnc_buyItem; };
case 303: { ["rhs_6b27m_ml", "Helmet 6B27M Mountain Les", "item"] call A3M_fnc_buyItem; };
case 304: { ["rhs_6b28_green", "Helmet 6B28 Plain", "item"] call A3M_fnc_buyItem; };
case 305: { ["rhs_6b28_green_ess", "Helmet 6B28 Plain (Goggles)", "item"] call A3M_fnc_buyItem; };
case 306: { ["rhs_6b28_green_bala", "Helmet 6B28 Plain (Balaclava)", "item"] call A3M_fnc_buyItem; };
case 307: { ["rhs_6b28_green_ess_bala", "Helmet 6B28 Plain (Goggles and Balaclava)", "item"] call A3M_fnc_buyItem; };
case 308: { ["rhs_6b28", "Helmet 6B28 EMR-Summer", "item"] call A3M_fnc_buyItem; };
case 309: { ["rhs_6b28_ess", "Helmet 6B28 EMR-Summer (Googles)", "item"] call A3M_fnc_buyItem; };
case 310: { ["rhs_6b28_bala", "Helmet 6B28 EMR-Summer (Balaclava)", "item"] call A3M_fnc_buyItem; };
case 311: { ["rhs_6b28_ess_bala", "Helmet 6B28 EMR-Summer (Goggles and Balaclava)", "item"] call A3M_fnc_buyItem; };
case 312: { ["rhs_6b28_flora", "Helmet 6B28 Flora", "item"] call A3M_fnc_buyItem; };
case 313: { ["rhs_6b28_flora_ess", "Helmet 6B28 Flora (Goggles)", "item"] call A3M_fnc_buyItem; };
case 314: { ["rhs_6b28_flora_bala", "Helmet 6B28 Flora (Balaclava)", "item"] call A3M_fnc_buyItem; };
case 315: { ["rhs_6b28_ess_bala", "Flora (Googles and Balaclava)", "item"] call A3M_fnc_buyItem; };
case 316: { ["rhs_Booniehat_flora", "Boonie Hat (Flora)", "item"] call A3M_fnc_buyItem; };
case 317: { ["rhs_Booniehat_digi", "Boonie Hat (EMR-Summer)", "item"] call A3M_fnc_buyItem; };
case 318: { ["rhs_beanie", "Beanie Flora", "item"] call A3M_fnc_buyItem; };
case 319: { ["rhs_beanie_green", "Beanie", "item"] call A3M_fnc_buyItem; };
case 320: { ["rhs_tsh4", "Tank Helmet TSh-4", "item"] call A3M_fnc_buyItem; };
case 321: { ["rhs_tsh4_ess", "Tank Helmet TSh-4 (Googles)", "item"] call A3M_fnc_buyItem; };
case 322: { ["rhs_tsh4_bala", "Tank Helmet TSh-4 (Balaclava)", "item"] call A3M_fnc_buyItem; };
case 323: { ["rhs_tsh4_ess_bala", "Tank Helmet TSh-4 (Googles and Balaclava)", "item"] call A3M_fnc_buyItem; };
case 324: { ["rhs_zsh7a_mike", "Pilot Helmet ZSh-7A", "item"] call A3M_fnc_buyItem; };
case 325: { ["rhs_zsh7a", "Pilot Helmet ZSh-7A (KM-35)", "item"] call A3M_fnc_buyItem; };
};
