switch (TheSelection) do {
	case 0 : { ["arifle_Katiba_C_F", "Katiba C 6.5mm", "weapon"] call A3M_fnc_buyItem; };
	case 1 : { ["arifle_Katiba_F", "Katiba F 6.5mm", "weapon"] call A3M_fnc_buyItem; };
	case 2 : { ["arifle_Katiba_GL_F", "Katiba F + GL 6.5mm", "weapon"] call A3M_fnc_buyItem; };
	case 3 : { ["arifle_Mk20_F", "Mk20 F 5.56mm", "weapon"] call A3M_fnc_buyItem; };
	case 4 : { ["arifle_Mk20_GL_F", "Mk20F + GL5.56mm", "weapon"] call A3M_fnc_buyItem; };
	case 5 : { ["arifle_Mk20C_plain_F", "Mk20C 5.56mm", "weapon"] call A3M_fnc_buyItem; };
	case 6 : { ["arifle_MX_Black_F", "MX (Black) 6.5mm", "weapon"] call A3M_fnc_buyItem; };
	case 7 : { ["arifle_MX_F", "MX-F 6.5mm", "weapon"] call A3M_fnc_buyItem; };
	case 8 : { ["arifle_MX_GL_F", "MX-F + GL 6.5mm", "weapon"] call A3M_fnc_buyItem; };
	case 9 : { ["arifle_MX_SW_Black_F", "MX-SW (Black) 6.5mm", "weapon"] call A3M_fnc_buyItem; };
	case 10 : { ["arifle_MX_SW_F", "MX-SW-F 6.5mm", "weapon"] call A3M_fnc_buyItem; };
	case 11 : { ["arifle_MXC_Black_F", "MX-C (Black) 6.5mm", "weapon"] call A3M_fnc_buyItem; };
	case 12 : { ["arifle_MXC_F", "MX-C-F 6.5mm", "weapon"] call A3M_fnc_buyItem; };
	case 13 : { ["arifle_MXM_Black_F", "MX-M (Black) 6.5mm", "weapon"] call A3M_fnc_buyItem; };
	case 14 : { ["arifle_MXM_F", "MX-M -F 6.5mm", "weapon"] call A3M_fnc_buyItem; };
	case 15 : { ["arifle_SDAR_F", "SDAR 5.56mm", "weapon"] call A3M_fnc_buyItem; };
	case 16 : { ["arifle_TRG20_F", "TRG-20 5.56mm", "weapon"] call A3M_fnc_buyItem; };
	case 17 : { ["arifle_TRG21_F", "TRG-21 5.56mm", "weapon"] call A3M_fnc_buyItem; };
	case 18 : { ["arifle_TRG21_GL_F", "TRG-21 + GL 5.56mm", "weapon"] call A3M_fnc_buyItem; };
	case 19 : { ["LMG_Mk200_F", "Mk200 6.5mm", "weapon"] call A3M_fnc_buyItem; };
	case 20 : { ["LMG_Zafir_F", "Zafir 7.62mm", "weapon"] call A3M_fnc_buyItem; };
	case 21 : { ["srifle_DMR_01_F", "Rahim 7.62mm", "weapon"] call A3M_fnc_buyItem; };
	case 22 : { ["srifle_EBR_F", "M-14 EBR 7.62mm", "weapon"] call A3M_fnc_buyItem; };
	case 23 : { ["srifle_GM6_F", "GM6 Lynx 12.7mm", "weapon"] call A3M_fnc_buyItem; };
	case 24 : { ["srifle_LRR_F", "M320 LRR .408", "weapon"] call A3M_fnc_buyItem; };
};
