switch (TheSelection) do {
    case 191 : {["UR_G_Bandanna_Beast_Avi", "Bandanna (Beast - Aviators)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 192 : {["UR_G_Bandanna_Beast_Grey_Avi", "Bandanna (Beast Grey - Aviators)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 193 : {["UR_G_Bandanna_Beast_Grey", "Bandanna (Beast Grey)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 194 : {["UR_G_Bandanna_Beast_Red_Avi", "Bandanna (Beast Red - Aviators)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 195 : {["UR_G_Bandanna_Beast_Red", "Bandanna (Beast Red)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 196 : {["UR_G_Bandanna_Kha_Avi", "Bandanna (Khaki - Aviators)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 197 : {["UR_G_Bandanna_Oli_Avi", "Bandanna (Olive - Aviators)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 198 : {["UR_G_Bandanna_Tan_Avi", "Bandanna (Tan - Aviators)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 199 : {["UR_G_Balaclava_ACU", "Uriki's Balaclava (ACU)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 200 : {["UR_G_Balaclava_Artic", "Uriki's Balaclava (Artic)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 201 : {["UR_G_Balaclava_Deadpool", "Uriki's Balaclava (Deadpool)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 202 : {["UR_G_Balaclava_Deathstroke", "Uriki's Balaclava (Deathstroke)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 203 : {["UR_G_Balaclava_Emile_Ard", "Uriki's Balaclava (Emile - Arid)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 204 : {["UR_G_Balaclava_Emile_Blk", "Uriki's Balaclava (Emile - Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 205 : {["UR_G_Balaclava_Emile_Lush", "Uriki's Balaclava (Emile - Lush)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 206 : {["UR_G_Balaclava_Flecktarn", "Uriki's Balaclava (Flecktarn)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 207 : {["UR_G_Balaclava_CodGhosts_01_Ard", "Uriki's Balaclava (Ghost 01 - Arid)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 208 : {["UR_G_Balaclava_CodGhosts_01_Blk", "Uriki's Balaclava (Ghost 01 - Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 209 : {["UR_G_Balaclava_CodGhosts_01_Blk_LPG", "Uriki's Balaclava (Ghost 01 - Black, Goggles)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 210 : {["UR_G_Balaclava_CodGhosts_01_Lsh", "Uriki's Balaclava (Ghost 01 - Lush)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 211 : {["UR_G_Balaclava_CodGhosts_02_Ard", "Uriki's Balaclava (Ghost 02 - Arid)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 212 : {["UR_G_Balaclava_CodGhosts_02_Blk", "Uriki's Balaclava (Ghost 02 - Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 213 : {["UR_G_Balaclava_CodGhosts_02_Blk_LPG", "Uriki's Balaclava (Ghost 02 - Black, Goggles)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 214 : {["UR_G_Balaclava_CodGhosts_02_Lsh", "Uriki's Balaclava (Ghost 02 - Lush)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 215 : {["UR_G_Balaclava_CodGhosts_03_Ard", "Uriki's Balaclava (Ghost 03 - Arid)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 216 : {["UR_G_Balaclava_CodGhosts_03_Blk", "Uriki's Balaclava (Ghost 03 - Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 217 : {["UR_G_Balaclava_CodGhosts_03_Blk_LPG", "Uriki's Balaclava (Ghost 03 - Black, Goggles)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 218 : {["UR_G_Balaclava_CodGhosts_03_Lsh", "Uriki's Balaclava (Ghost 03 - Lush)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 219 : {["UR_G_Balaclava_Marpat_Des", "Uriki's Balaclava (Marpat Desert)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 220 : {["UR_G_Balaclava_Marpat_Wood", "Uriki's Balaclava (Marpat Woodland)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 221 : {["UR_G_Balaclava_Wood", "Uriki's Balaclava (Woodland)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 222 : {["UR_G_Balaclava_clownCigar", "Uriki's Balaclava (Cigar Clown, Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 223 : {["UR_G_Balaclava_clownColour", "Uriki's Balaclava (Color Clown, Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 224 : {["UR_G_Balaclava_CodGhost", "Uriki's Balaclava (Ghost 04 - Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 225 : {["UR_G_Balaclava_mouthDirty", "Uriki's Balaclava (Mouth Dirty - Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 226 : {["UR_G_Balaclava_mouthSnarl", "Uriki's Balaclava (Mouth Snarl - Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 227 : {["UR_G_Balaclava_GhostRecon_Black", "Uriki's Balaclava (Recon - Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 228 : {["UR_G_Balaclava_Ghostrecon_Green", "Uriki's Balaclava (Recon - Green)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 229 : {["UR_G_Balaclava_GhostRecon_Khaki", "Uriki's Balaclava (Recon - Khaki)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 230 : {["UR_G_Balaclava_Skull_01_Black_Avi", "Uriki's Balaclava (Skull 01 - Aviators Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 231 : {["UR_G_Balaclava_Skull_01_Black", "Uriki's Balaclava (Skull 01 - Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 232 : {["UR_G_Balaclava_Skull_01_Green", "Uriki's Balaclava (Skull 01 - Green)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 233 : {["UR_G_Balaclava_Skull_01_Khaki", "Uriki's Balaclava (Skull 01 - Khaki)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 234 : {["UR_G_Balaclava_tribal_01_Black", "Uriki's Balaclava (Tribal 01 - Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 235 : {["UR_G_Balaclava_tribal_01_Green", "Uriki's Balaclava (Tribal 01 - Green)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 236 : {["UR_G_Balaclava_tribal_01_Khaki", "Uriki's Balaclava (Tribal 01 - Khaki)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 237 : {["UR_G_Balaclava_tribal_02_Black", "Uriki's Balaclava (Tribal 02 - Black)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 238 : {["UR_G_Balaclava_tribal_02_Green", "Uriki's Balaclava (Tribal 02 - Green)", "TypeOfItem"] call A3M_fnc_buyItem; };
    case 239 : {["UR_G_Balaclava_tribal_02_Khaki", "Uriki's Balaclava (Tribal 02 - Khaki)", "TypeOfItem"] call A3M_fnc_buyItem; };
};
