switch (TheSelection) do {
	case 0: { ["U_B_CombatUniform_mcam", "U.S. MultiCam Uni 1", "item"] call A3M_fnc_buyItem; };
	case 1: { ["U_B_CombatUniform_mcam_tshirt", "U.S. MultiCam Uni 2", "item"] call A3M_fnc_buyItem; };
	case 2: { ["U_B_CombatUniform_mcam_vest", "U.S. MultiCam Uni 3", "item"] call A3M_fnc_buyItem; };
	case 3: { ["U_B_CombatUniform_mcam_worn", "U.S. MultiCam Uni 4", "item"] call A3M_fnc_buyItem; };
	case 4: { ["U_B_CombatUniform_sgg", "U.S. MultiCam Uni 5", "item"] call A3M_fnc_buyItem; };
	case 5: { ["U_B_CombatUniform_sgg_tshirt", "U.S. MultiCam Uni 6", "item"] call A3M_fnc_buyItem; };
	case 6: { ["U_B_CombatUniform_sgg_vest", "U.S. MultiCam Uni 7", "item"] call A3M_fnc_buyItem; };
	case 7: { ["U_B_CombatUniform_wdl", "U.S. MultiCam Uni 8", "item"] call A3M_fnc_buyItem; };
	case 8: { ["U_B_CombatUniform_wdl_tshirt", "U.S. MultiCam Uni 9", "item"] call A3M_fnc_buyItem; };
	case 9: { ["U_B_CombatUniform_wdl_vest", "U.S. MultiCam Uni 1", "item"] call A3M_fnc_buyItem; };
	case 10: { ["U_B_CTRG_1", "U.K. Multicam Uni 1", "item"] call A3M_fnc_buyItem; };
	case 11: { ["U_B_CTRG_2", "U.K. Multicam Uni 2", "item"] call A3M_fnc_buyItem; };
	case 12: { ["U_B_CTRG_3", "U.K. Multicam Uni 3", "item"] call A3M_fnc_buyItem; };
	case 13: { ["U_B_GhillieSuit", "Marksman Partial Ghillie Suit", "item"] call A3M_fnc_buyItem; };
	case 14: { ["U_B_HeliPilotCoveralls", "Pilot Coveralls (Heli)", "item"] call A3M_fnc_buyItem; };
	case 15: { ["U_B_PilotCoveralls", "Flight Suit", "item"] call A3M_fnc_buyItem; };
	case 16: { ["U_B_SpecopsUniform_sgg", "U.S. Specops Uni 1", "item"] call A3M_fnc_buyItem; };
	case 17: { ["U_BG_Guerilla1_1", "Casual Combat 1", "item"] call A3M_fnc_buyItem; };
	case 18: { ["U_BG_Guerilla2_1", "Casual Combat 2", "item"] call A3M_fnc_buyItem; };
	case 19: { ["U_BG_Guerilla2_2", "Casual Combat 3", "item"] call A3M_fnc_buyItem; };
	case 20: { ["U_BG_Guerilla2_3", "Casual Combat 4", "item"] call A3M_fnc_buyItem; };
	case 21: { ["U_BG_Guerilla3_1", "Casual Combat 5", "item"] call A3M_fnc_buyItem; };
	case 22: { ["U_BG_Guerilla3_2", "Casual Combat 6", "item"] call A3M_fnc_buyItem; };
	case 23: { ["U_BG_leader", "Casual Combat 7", "item"] call A3M_fnc_buyItem; };
	case 24: { ["U_C_HunterBody_brn", "Casual Combat 8", "item"] call A3M_fnc_buyItem; };
	case 25: { ["U_C_HunterBody_grn", "Casual Combat 9", "item"] call A3M_fnc_buyItem; };
	case 26: { ["U_I_CombatUniform", "Casual Combat 10", "item"] call A3M_fnc_buyItem; };
	case 27: { ["U_I_CombatUniform_shortsleeve", "Casual Combat 11", "item"] call A3M_fnc_buyItem; };
	case 28: { ["U_I_CombatUniform_tshirt", "Casual Combat 12", "item"] call A3M_fnc_buyItem; };
	case 29: { ["U_I_G_resistanceLeader_F", "Casual Combat 13", "item"] call A3M_fnc_buyItem; };
	case 30: { ["U_IG_Guerilla1_1", "Casual Combat 14", "item"] call A3M_fnc_buyItem; };
	case 31: { ["U_IG_Guerilla2_1", "Casual Combat 15", "item"] call A3M_fnc_buyItem; };
	case 32: { ["U_IG_Guerilla2_2", "Casual Combat 16", "item"] call A3M_fnc_buyItem; };
	case 33: { ["U_IG_Guerilla2_3", "Casual Combat 1", "item"] call A3M_fnc_buyItem; };
	case 34: { ["U_IG_Guerilla3_1", "Casual Combat 18", "item"] call A3M_fnc_buyItem; };
	case 35: { ["U_IG_Guerilla3_2", "Casual Combat 19", "item"] call A3M_fnc_buyItem; };
	case 36: { ["U_IG_leader", "Casual Combat 20", "item"] call A3M_fnc_buyItem; };
	case 37: { ["U_OG_Guerilla1_1", "Casual Combat 21", "item"] call A3M_fnc_buyItem; };
	case 38: { ["U_OG_Guerilla2_1", "Casual Combat 22", "item"] call A3M_fnc_buyItem; };
	case 39: { ["U_OG_Guerilla2_2", "Casual Combat 23", "item"] call A3M_fnc_buyItem; };
	case 40: { ["U_OG_Guerilla2_3", "Casual Combat 24", "item"] call A3M_fnc_buyItem; };
	case 41: { ["U_OG_Guerilla3_1", "Casual Combat 25", "item"] call A3M_fnc_buyItem; };
	case 42: { ["U_OG_Guerilla3_2", "Casual Combat 26", "item"] call A3M_fnc_buyItem; };
	case 43: { ["U_OG_leader", "Casual Combat 27", "item"] call A3M_fnc_buyItem; };
};
