switch (TheSelection) do {
    case 0: { ["V_BandollierB_blk", "Bianchi Light Duty Belt - blk", "deliveries"] call A3M_fnc_buyItem; };
    case 1: { ["V_BandollierB_cbr", "Bianchi Light Duty Belt - cbr", "deliveries"] call A3M_fnc_buyItem; };
    case 2: { ["V_BandollierB_khk", "Bianchi Light Duty Belt - khk", "deliveries"] call A3M_fnc_buyItem; };
    case 3: { ["V_BandollierB_oli", "Bianchi Light Duty Belt - oli", "deliveries"] call A3M_fnc_buyItem; };
    case 4: { ["V_BandollierB_rgr", "Bianchi Light Duty Belt - rgr", "deliveries"] call A3M_fnc_buyItem; };
    case 5: { ["V_Chestrig_blk", "Uncle Mike's Light Tactical - blk", "deliveries"] call A3M_fnc_buyItem; };
    case 6: { ["V_Chestrig_khk", "Uncle Mike's Light Tactical - khk", "deliveries"] call A3M_fnc_buyItem; };
    case 7: { ["V_Chestrig_oli", "Uncle Mike's Light Tactical - oli", "deliveries"] call A3M_fnc_buyItem; };
    case 8: { ["V_Chestrig_rgr", "Uncle Mike's Light Tactical - rgr", "deliveries"] call A3M_fnc_buyItem; };
    case 9: { ["V_HarnessO_gry", "TacticalOne Eagle Light Tactical - Brn", "deliveries"] call A3M_fnc_buyItem; };
    case 10: { ["V_HarnessOGL_brn", "TacticalOne Talon Light Tactical - Brn", "deliveries"] call A3M_fnc_buyItem; };
    case 11: { ["V_HarnessOSpec_brn", "TacticalOne Eagle Two Light Tactical - Brn", "deliveries"] call A3M_fnc_buyItem; };
    case 12: { ["V_I_G_resistanceLeader_F", "GenII Assault Vest", "deliveries"] call A3M_fnc_buyItem; };
    case 13: { ["V_PlateCarrier1_blk", "SecondChance Tactical Armor - BLK", "deliveries"] call A3M_fnc_buyItem; };
    case 14: { ["V_PlateCarrier1_rgr", "SecondChance Tactical Armor - RGR", "deliveries"] call A3M_fnc_buyItem; };
    case 15: { ["V_PlateCarrier2_rgr", "SecondChance Defender Armor - RGR", "deliveries"] call A3M_fnc_buyItem; };
    case 16: { ["V_PlateCarrier3_rgr", "SecondChance Interceptor Armor - RGR", "deliveries"] call A3M_fnc_buyItem; };
    case 17: { ["V_PlateCarrierGL_rgr", "SecondChance MXL Armor - RGR", "deliveries"] call A3M_fnc_buyItem; };
    case 18: { ["V_PlateCarrierH_CTRG", "SecondChance Tactical Armor - CTR", "deliveries"] call A3M_fnc_buyItem; };
    case 19: { ["V_PlateCarrierIA1_dgtl", "SecondChance Tactical II Armor - DGTL", "deliveries"] call A3M_fnc_buyItem; };
    case 20: { ["V_PlateCarrierIA2_dgtl", "SecondChance Defender II Armor - DGTL", "deliveries"] call A3M_fnc_buyItem; };
    case 21: { ["V_PlateCarrierIAGL_dgtl", "SecondChance MXL II Armor - DGTL", "deliveries"] call A3M_fnc_buyItem; };
    case 22: { ["V_PlateCarrierL_CTRG", "SecondChance Tactical Armor - CTRG", "deliveries"] call A3M_fnc_buyItem; };
    case 23: { ["V_PlateCarrierSpec_rgr", "SecondChance MAXIMUS Armor - RGR", "deliveries"] call A3M_fnc_buyItem; };
    case 24: { ["V_RebreatherIA", "SCUBAChoice Rebreather Kit", "deliveries"] call A3M_fnc_buyItem; };
    case 25: { ["V_TacVest_blk", "Intelitec Load Bearing Vest IIA - BLK", "deliveries"] call A3M_fnc_buyItem; };
    case 26: { ["V_TacVest_blk_POLICE", "SecondChance BreachTech Armor - BLK", "deliveries"] call A3M_fnc_buyItem; };
    case 27: { ["V_TacVest_brn", "Intelitec Load Bearing Vest IIA - BRN", "deliveries"] call A3M_fnc_buyItem; };
    case 28: { ["V_TacVest_camo", "Intelitec Load Bearing Vest IIA - CAMO", "deliveries"] call A3M_fnc_buyItem; };
    case 29: { ["V_TacVest_khk", "Intelitec Load Bearing Vest IIA - KHK", "deliveries"] call A3M_fnc_buyItem; };
    case 30: { ["V_TacVest_oli", "Intelitec Load Bearing Vest IIA - OLI", "deliveries"] call A3M_fnc_buyItem; };
    case 31: { ["V_TacVestCamo_khk", "General Protection IIIA Armor - CAMO", "deliveries"] call A3M_fnc_buyItem; };
    case 32: { ["V_TacVestIR_blk", "Raven Tactical Supply Stealth Armor", "deliveries"] call A3M_fnc_buyItem; };
};
