switch (TheSelection) do {
    case 0 : {["sgun_aa40_lxWS", "AA12", "weapon"] call A3M_fnc_buyItem; };
    case 1 : {["sgun_aa40_tan_lxWS", "AA12 (Sand)", "weapon"] call A3M_fnc_buyItem; };
    case 2 : {["sgun_aa40_snake_lxWS", "AA12 (Snake)", "weapon"] call A3M_fnc_buyItem; };
    case 3 : {["arifle_SLR_V_lxWS", "FN FAL 50.00", "weapon"] call A3M_fnc_buyItem; };
    case 4 : {["arifle_SLR_D_lxWS", "FN FAL 50.00 (Desert)", "weapon"] call A3M_fnc_buyItem; };
    case 5 : {["arifle_SLR_V_camo_lxWS", "FN FAL 50.00 (Jungle)", "weapon"] call A3M_fnc_buyItem; };
    case 6 : {["arifle_SLR_lxWS", "FN FAL 50.00 (Wood)", "weapon"] call A3M_fnc_buyItem; };
    case 7 : {["arifle_SLR_V_GL_lxWS", "FN FAL 50.00 GL", "weapon"] call A3M_fnc_buyItem; };
    case 8 : {["arifle_SLR_GL_lxWS", "FN FAL 50.00 GL (Wood)", "weapon"] call A3M_fnc_buyItem; };
    case 9 : {["arifle_SLR_Para_lxWS", "FN FAL OSW Para", "weapon"] call A3M_fnc_buyItem; };
    case 10 : {["arifle_SLR_Para_snake_lxWS", "FN FAL OSW Para (Snake)", "weapon"] call A3M_fnc_buyItem; };
    case 11 : {["arifle_Galat_lxWS", "Galat ARM", "weapon"] call A3M_fnc_buyItem; };
    case 12 : {["arifle_Galat_worn_lxWS", "Galat ARM (Old)", "weapon"] call A3M_fnc_buyItem; };
    case 13 : {["glaunch_GLX_lxWS", "GLX 160", "weapon"] call A3M_fnc_buyItem; };
    case 14 : {["glaunch_GLX_camo_lxWS", "GLX 160 (Camo)", "weapon"] call A3M_fnc_buyItem; };
    case 15 : {["glaunch_GLX_ghex_lxWS", "GLX 160 (Green Hex)", "weapon"] call A3M_fnc_buyItem; };
    case 16 : {["glaunch_GLX_hex_lxWS", "GLX 160 (Hex)", "weapon"] call A3M_fnc_buyItem; };
    case 17 : {["glaunch_GLX_tan_lxWS", "GLX 160 (Sand)", "weapon"] call A3M_fnc_buyItem; };
    case 18 : {["glaunch_GLX_snake_lxWS", "GLX 160 (Snake)", "weapon"] call A3M_fnc_buyItem; };
    case 19 : {["srifle_GM6_snake_lxWS", "GM6 Lynx (Snake)", "weapon"] call A3M_fnc_buyItem; };
    case 20 : {["srifle_EBR_blk_lxWS", "Mk14 Mod 1 EBR (Black)", "weapon"] call A3M_fnc_buyItem; };
    case 21 : {["srifle_EBR_snake_lxWS", "Mk14 Mod 1 EBR (Snake)", "weapon"] call A3M_fnc_buyItem; };
    case 22 : {["arifle_Velko_lxWS", "Vektor R4", "weapon"] call A3M_fnc_buyItem; };
    case 23 : {["arifle_VelkoR5_lxWS", "Vektor R5 Carbine", "weapon"] call A3M_fnc_buyItem; };
    case 24 : {["arifle_VelkoR5_snake_lxWS", "Vektor R5 Carbine (Snake)", "weapon"] call A3M_fnc_buyItem; };
    case 25 : {["arifle_VelkoR5_GL_lxWS", "Vektor R5 Carbine GL", "weapon"] call A3M_fnc_buyItem; };
    case 26 : {["arifle_VelkoR5_GL_snake_lXWS", "Vektor R5 Carbine GL (Snake)", "weapon"] call A3M_fnc_buyItem; };
    case 27 : {["LMG_S77_lxWS", "Vektor SS-77", "weapon"] call A3M_fnc_buyItem; };
    case 28 : {["LMG_S77_AAF_lxWS", "Vektor SS-77 (Camo)", "weapon"] call A3M_fnc_buyItem; };
    case 29 : {["LMG_S77_Desert_lxWS", "Vektor SS-77 (Desert)", "weapon"] call A3M_fnc_buyItem; };
    case 30 : {["LMG_S77_GHex_lxWS", "Vektor SS-77 (Green Hex)", "weapon"] call A3M_fnc_buyItem; };
    case 31 : {["LMG_S77_Hex_lxWS", "Vektor SS-77 (Hex)", "weapon"] call A3M_fnc_buyItem; };
    case 32 : {["LMG_S77_Compact_lxWS", "Vektor SS-77 Compact", "weapon"] call A3M_fnc_buyItem; };
    case 33 : {["LMG_S77_Compact_Snakeskin_lxWS", "Vektor SS-77 Compact (Snake)", "weapon"] call A3M_fnc_buyItem; };
    case 34 : {["arifle_XMS_lxWS", "XMS", "weapon"] call A3M_fnc_buyItem; };
    case 35 : {["arifle_XMS_Gray_lxWS", "XMS (Gray)", "weapon"] call A3M_fnc_buyItem; };
    case 36 : {["arifle_XMS_khk_lxWS", "XMS (Khaki)", "weapon"] call A3M_fnc_buyItem; };
    case 37 : {["arifle_XMS_Sand_lxWS", "XMS (Sand)", "weapon"] call A3M_fnc_buyItem; };
    case 38 : {["arifle_XMS_Camo_lxWS", "XMS (Stripes)", "weapon"] call A3M_fnc_buyItem; };
    case 39 : {["arifle_XMS_GL_lxWS", "XMS GL", "weapon"] call A3M_fnc_buyItem; };
    case 40 : {["arifle_XMS_GL_Gray_lxWS", "XMS GL (Gray)", "weapon"] call A3M_fnc_buyItem; };
    case 41 : {["arifle_XMS_GL_khk_lxWS", "XMS GL (Khaki)", "weapon"] call A3M_fnc_buyItem; };
    case 42 : {["arifle_XMS_GL_Sand_lxWS", "XMS GL (Sand)", "weapon"] call A3M_fnc_buyItem; };
    case 43 : {["arifle_XMS_GL_Camo_lxWS", "XMS GL (Stripes)", "weapon"] call A3M_fnc_buyItem; };
    case 44 : {["arifle_XMS_Shot_lxWS", "XMS SG", "weapon"] call A3M_fnc_buyItem; };
    case 45 : {["arifle_XMS_Shot_Gray_lxWS", "XMS SG (Gray)", "weapon"] call A3M_fnc_buyItem; };
    case 46 : {["arifle_XMS_Shot_khk_lxWS", "XMS SG (Khaki)", "weapon"] call A3M_fnc_buyItem; };
    case 47 : {["arifle_XMS_Shot_Sand_lxWS", "XMS SG (Sand)", "weapon"] call A3M_fnc_buyItem; };
    case 48 : {["arifle_XMS_Shot_Camo_lxWS", "XMS SG (Stripes)", "weapon"] call A3M_fnc_buyItem; };
    case 49 : {["arifle_XMS_M_lxWS", "XMS SW", "weapon"] call A3M_fnc_buyItem; };
    case 50 : {["arifle_XMS_M_Gray_lxWS", "XMS SW (Gray)", "weapon"] call A3M_fnc_buyItem; };
    case 51 : {["arifle_XMS_M_khk_lxWS", "XMS SW (Khaki)", "weapon"] call A3M_fnc_buyItem; };
    case 52 : {["arifle_XMS_M_Sand_lxWS", "XMS SW (Sand)", "weapon"] call A3M_fnc_buyItem; };
    case 53 : {["arifle_XMS_M_Camo_lxWS", "XMS SW (Stripes)", "weapon"] call A3M_fnc_buyItem; };
};
