switch (TheSelection) do {
    case 21: { ["Camera_lxWS", "Digital Camera", "item"] call A3M_fnc_buyItem; };
    case 22: { ["ItemMotionSensor_lxWS", "Motion Sensor", "item"] call A3M_fnc_buyItem; };
    case 23 : {["acc_pointer_IR_arid_lxWS", "IR Laser Pointer (Arid)", "item"] call A3M_fnc_buyItem; };
    case 24 : {["acc_pointer_IR_lush_lxWS", "IR Laser Pointer (Lush)", "item"] call A3M_fnc_buyItem; };
    case 25 : {["acc_pointer_IR_sand_lxWS", "IR Laser Pointer (Sand)", "item"] call A3M_fnc_buyItem; };
    case 26 : {["acc_pointer_IR_snake_lxWS", "IR Laser Pointer (Snake)", "item"] call A3M_fnc_buyItem; };
    case 27 : {["saber_light_lxWS", "Saber Light", "item"] call A3M_fnc_buyItem; };
    case 28 : {["saber_light_arid_lxWS", "Saber Light (Arid)", "item"] call A3M_fnc_buyItem; };
    case 29 : {["saber_light_khaki_lxWS", "Saber Light (Khaki)", "item"] call A3M_fnc_buyItem; };
    case 30 : {["saber_light_lush_lxWS", "Saber Light (Lush)", "item"] call A3M_fnc_buyItem; };
    case 31 : {["saber_light_sand_lxWS", "Saber Light (Sand)", "item"] call A3M_fnc_buyItem; };
    case 32 : {["saber_light_snake_lxWS", "Saber Light (Snake)", "item"] call A3M_fnc_buyItem; };
    case 33 : {["saber_light_ir_lxWS", "Saber Light IR", "item"] call A3M_fnc_buyItem; };
    case 34 : {["saber_light_ir_arid_lxWS", "Saber Light IR (Arid)", "item"] call A3M_fnc_buyItem; };
    case 35 : {["saber_light_ir_khaki_lxWS", "Saber Light IR (Khaki)", "item"] call A3M_fnc_buyItem; };
    case 36 : {["saber_light_ir_lush_lxWS", "Saber Light IR (Lush)", "item"] call A3M_fnc_buyItem; };
    case 37 : {["saber_light_ir_sand_lxWS", "Saber Light IR (Sand)", "item"] call A3M_fnc_buyItem; };
    case 38 : {["saber_light_ir_snake_lxWS", "Saber Light IR (Snake)", "item"] call A3M_fnc_buyItem; };
};
