private _rank = rank player;

switch (TheSelection) do {
    case 5: { ["rhs_ch_47f_10", "USA (Army 2010) CH-47", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 6: { ["rhs_ch_47f_light_10", "USA (Army 2010) CH-47 (D)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 7: { ["rhs_ch_47f", "USA (Army 2014) CH-47", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 8: { ["rhs_ch_47f_light", "USA (Army 2014) CH-47 (D)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 9: { ["rhs_uh1y", "USA (USMC 2010) UH-1Y (FFAR/MG)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 10: { ["rhs_uh1y_ffar", "USA (USMC 2010) UH-1Y (FFAR)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 11: { ["rhs_uh1y_unarmed", "USA (USMC 2010) UH-1Y (Unarmed)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 12: { ["rhs_uh60m", "USA (Army 2014) UH-60M", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 13: { ["rhs_uh60m_mev2", "USA (Army 2014) UH-60M MEV", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 14: { ["rhs_uh60m_mev", "USA (Army 2014) UH-60M MEV (ESSS)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 15: { ["RHS_Ka52_vvs", "RUS Ka-52 (Grey)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 16: { ["RHS_Ka52_vvsc", "RUS Ka-52 (Camo)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 17: { ["rhs_ka60_grey", "RUS Ka-60 (Grey)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 18: { ["rhs_ka60_c", "RUS Ka-60 (Camo)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 19: { ["RHS_Mi24P_vdv", "RUS Mi-24P", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 20: { ["RHS_Mi24V_vdv", "RUS Mi-24V", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 21: { ["RHS_Mi24P_vvs", "RUS Mi-24P (Grey)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 22: { ["RHS_Mi24V_vvs", "RUS Mi-24V (Grey)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 23: { ["RHS_Mi24P_vvsc", "RUS Mi-24P (Camo)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 24: { ["RHS_Mi24V_vvsc", "RUS Mi-24V (Camo)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 25: { ["RHS_Mi8AMT_vdv", "RUS Mi-8AMT", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 26: { ["RHS_Mi8AMTSh_vdv", "RUS Mi-8AMTSh", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 27: { ["RHS_Mi8AMT_vvs", "RUS Mi-8AMT (Grey)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 28: { ["RHS_Mi8AMTSh_vvs", "RUS Mi-8AMTSh (Grey)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 29: { ["RHS_Mi8AMT_vvsc", "RUS Mi-8AMT (Camo)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 30: { ["RHS_Mi8AMTSh_vvsc", "RUS Mi-8AMTSh (Camo)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 31: { ["RHS_Mi8mt_vdv", "RUS Mi-8MT", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 32: { ["RHS_Mi8MTV3_vdv", "RUS Mi-8MTV-3", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 33: { ["RHS_Mi8mt_vvs", "RUS Mi-8MT (Grey)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 34: { ["RHS_Mi8MTV3_vvs", "RUS Mi-8MTV-3 (Grey)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 35: { ["RHS_Mi8mt_vvsc", "RUS Mi-8MT (Camo)", "vehspawn"] call A3M_fnc_buyVehicle; };
    case 36: { ["RHS_Mi8MTV3_vvsc", "RUS Mi-8MTV-3 (Camo)", "vehspawn"] call A3M_fnc_buyVehicle; };
};
